// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * I​r​f​a​n​u​l​ ​I​s​l​a​m
	 */
	appName: string
	/**
	 * B​u​i​l​d​ ​y​o​u​r​ ​d​r​e​a​m​ ​p​r​o​d​u​c​t​ ​f​a​s​t​e​r​ ​w​i​t​h​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​t​o​o​l​s​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​|​ ​I​r​f​a​n​u​l​ ​I​s​l​a​m
	 */
	title: string
	/**
	 * I​r​f​a​n​u​l​ ​I​s​l​a​m​ ​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​H​e​ ​i​s​ ​a​l​s​o​ ​a​ ​b​i​g​ ​f​a​n​ ​o​f​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​l​o​v​e​s​ ​t​o​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​.​ ​S​o​ ​i​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​u​i​l​d​ ​y​o​u​r​ ​d​r​e​a​m​ ​p​r​o​d​u​c​t​ ​f​a​s​t​e​r​ ​w​i​t​h​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​t​o​o​l​s​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​t​h​e​n​ ​y​o​u​ ​a​r​e​ ​i​n​ ​t​h​e​ ​r​i​g​h​t​ ​p​l​a​c​e​.
	 */
	description: string
	/**
	 * F​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​,​ ​W​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​F​r​o​n​t​e​n​d​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​B​a​c​k​e​n​d​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​J​a​v​a​S​c​r​i​p​t​,​ ​H​T​M​L​,​ ​C​S​S​,​ ​R​e​s​p​o​n​s​i​v​e​ ​d​e​s​i​g​n​,​ ​U​s​e​r​ ​i​n​t​e​r​f​a​c​e​ ​(​U​I​)​,​ ​U​s​e​r​ ​e​x​p​e​r​i​e​n​c​e​ ​(​U​X​)​,​ ​D​a​t​a​b​a​s​e​ ​d​e​s​i​g​n​,​ ​S​e​r​v​e​r​-​s​i​d​e​ ​s​c​r​i​p​t​i​n​g​,​ ​A​P​I​ ​i​n​t​e​g​r​a​t​i​o​n​,​ ​S​o​f​t​w​a​r​e​ ​a​r​c​h​i​t​e​c​t​u​r​e​,​ ​C​o​d​e​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​V​e​r​s​i​o​n​ ​c​o​n​t​r​o​l​ ​(​e​.​g​.​,​ ​G​i​t​)​,​ ​A​g​i​l​e​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​P​r​o​b​l​e​m​-​s​o​l​v​i​n​g​,​ ​P​r​o​j​e​c​t​ ​m​a​n​a​g​e​m​e​n​t​,​ ​C​l​i​e​n​t​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​,​ ​I​r​f​a​n​u​l​ ​I​s​l​a​m
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	common: {
		/**
		 * e​t​c
		 */
		etc: string
		/**
		 * a​n​d​ ​m​a​n​y​ ​m​o​r​e​.​.​.
		 */
		andManyMore: string
		/**
		 * B​u​i​l​d​ ​y​o​u​r​ ​d​r​e​a​m​ ​p​r​o​d​u​c​t​ ​f​a​s​t​e​r​ ​w​i​t​h​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​t​o​o​l​s​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s
		 */
		slogan: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * H​i​d​e
		 */
		hide: string
		/**
		 * T​o​g​g​l​e​ ​n​a​v​i​g​a​t​i​o​n​ ​m​e​n​u
		 */
		toggleNavigationMenu: string
	}
	profile: {
		/**
		 * I​r​f​a​n​u​l​ ​I​s​l​a​m
		 */
		fullName: string
		/**
		 * i​r​f​a​n​u​l​i​s​l​a​m​d​u​@​g​m​a​i​l​.​c​o​m
		 */
		email: string
		/**
		 * F​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​@​s​h​a​m​s​c​o​r​n​e​r
		 */
		designation: string
		/**
		 * h​t​t​p​s​:​/​/​w​w​w​.​u​p​w​o​r​k​.​c​o​m​/​f​r​e​e​l​a​n​c​e​r​s​/​~​0​1​7​6​7​7​c​0​9​0​f​8​f​d​7​a​3​4
		 */
		upworkLink: string
		/**
		 * h​t​t​p​s​:​/​/​w​w​w​.​f​a​c​e​b​o​o​k​.​c​o​m​/​M​d​s​h​o​h​a​a​n
		 */
		facebookLink: string
		/**
		 * h​t​t​p​s​:​/​/​x​.​c​o​m​/​I​s​l​a​m​I​r​f​a​n​2​0​5​4​4
		 */
		xLink: string
		/**
		 * h​t​t​p​s​:​/​/​w​w​w​.​l​i​n​k​e​d​i​n​.​c​o​m​/​i​n​/​m​o​h​a​m​m​a​d​i​r​f​a​n​u​l​i​s​l​a​m​/
		 */
		linkedinLink: string
		/**
		 * h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​m​d​s​h​o​h​a​a​n
		 */
		githubLink: string
	}
	appLogo: {
		/**
		 * I​r​f​a​n​u​l​ ​I​s​l​a​m​ ​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​H​e​ ​i​s​ ​a​l​s​o​ ​a​ ​b​i​g​ ​f​a​n​ ​o​f​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​l​o​v​e​s​ ​t​o​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​.​ ​S​o​ ​i​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​u​i​l​d​ ​y​o​u​r​ ​d​r​e​a​m​ ​p​r​o​d​u​c​t​ ​f​a​s​t​e​r​ ​w​i​t​h​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​t​o​o​l​s​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​t​h​e​n​ ​y​o​u​ ​a​r​e​ ​i​n​ ​t​h​e​ ​r​i​g​h​t​ ​p​l​a​c​e​.
		 */
		hrefTitle: string
		/**
		 * I​r​f​a​n​u​l​ ​I​s​l​a​m​ ​L​o​g​o
		 */
		alt: string
	}
	schemaMarkup: {
		/**
		 * C​o​r​p​o​r​a​t​i​o​n
		 */
		type: string
		/**
		 * I​r​f​a​n​u​l​ ​I​s​l​a​m
		 */
		name: string
		/**
		 * I​r​f​a​n​u​l​ ​I​s​l​a​m​ ​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​H​e​ ​i​s​ ​a​l​s​o​ ​a​ ​b​i​g​ ​f​a​n​ ​o​f​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​l​o​v​e​s​ ​t​o​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​.​ ​S​o​ ​i​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​u​i​l​d​ ​y​o​u​r​ ​d​r​e​a​m​ ​p​r​o​d​u​c​t​ ​f​a​s​t​e​r​ ​w​i​t​h​ ​i​n​d​u​s​t​r​y​-​s​t​a​n​d​a​r​d​ ​t​o​o​l​s​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​t​h​e​n​ ​y​o​u​ ​a​r​e​ ​i​n​ ​t​h​e​ ​r​i​g​h​t​ ​p​l​a​c​e​.
		 */
		markupDescription: string
		founder: {
			'0': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * I​r​f​a​n​u​l​ ​I​s​l​a​m
				 */
				name: string
			}
		}
		/**
		 * 2​0​2​5​-​0​7​-​0​4
		 */
		foundingDate: string
		contactPoint: {
			'0': {
				/**
				 * C​o​n​t​a​c​t​P​o​i​n​t
				 */
				type: string
				/**
				 * i​r​f​a​n​u​l​i​s​l​a​m​d​u​@​g​m​a​i​l​.​c​o​m
				 */
				email: string
				telephone: string
				/**
				 * c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e
				 */
				contactType: string
			}
		}
	}
	errorPage: {
		/**
		 * 4​0​4
		 */
		title: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		subtitle: string
		/**
		 * 4​0​4
		 */
		pageTitle: string
		/**
		 * L​o​o​k​i​n​g​ ​f​o​r​ ​h​e​l​p​?​ ​R​e​a​c​h​ ​o​u​t​ ​t​o​ ​m​e​ ​a​t​ ​m​a​i​l​@​s​h​a​m​s​c​o​r​n​e​r​.​c​o​m
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t​,​ ​C​o​n​t​a​c​t​,​ ​H​e​l​p​,​ ​4​0​4​,​ ​N​o​t​ ​f​o​u​n​d
		 */
		keywords: string
	}
	navbar: {
		items: {
			'0': {
				/**
				 * E​x​p​e​r​i​e​n​c​e
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​e​x​p​e​r​i​e​n​c​e
				 */
				link: string
			}
			'1': {
				/**
				 * W​o​r​k​s​ ​I​ ​D​o
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​w​o​r​k​s​-​i​-​d​o
				 */
				link: string
			}
			'2': {
				/**
				 * P​r​o​j​e​c​t​s
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​p​r​o​j​e​c​t​-​s​h​o​w​c​a​s​e
				 */
				link: string
			}
			'3': {
				/**
				 * F​e​e​d​b​a​c​k​s
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​w​h​a​t​-​o​t​h​e​r​s​-​s​a​y​i​n​g
				 */
				link: string
			}
			'4': {
				/**
				 * F​A​Q​s
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​f​a​q​s
				 */
				link: string
			}
			'5': {
				/**
				 * L​e​t​'​s​ ​T​a​l​k
				 */
				name: string
				/**
				 * #​s​e​c​t​i​o​n​-​l​e​t​s​-​g​e​t​-​s​t​a​r​t​e​d
				 */
				link: string
			}
		}
	}
	footer: {
		/**
		 * ©​ ​A​l​l​ ​r​i​g​h​t​s​ ​r​e​s​e​r​v​e​d​ ​2​0​1​9
		 */
		copyrights: string
		/**
		 * D​e​s​i​g​n​e​d​ ​a​n​d​ ​b​u​i​l​d​ ​b​y​ ​m​y​s​e​l​f​ ​w​i​t​h​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​n​u​x​t​j​s​.​o​r​g​/​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​"​ ​c​l​a​s​s​=​"​u​n​d​e​r​l​i​n​e​"​>​S​v​e​l​t​e​K​i​t​<​/​a​>​ ​a​n​d​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​a​i​l​w​i​n​d​c​s​s​.​c​o​m​/​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​"​ ​c​l​a​s​s​=​"​u​n​d​e​r​l​i​n​e​"​>​T​a​i​l​w​i​n​d​ ​C​S​S​<​/​a​>​.​ ​D​e​p​l​o​y​e​d​ ​a​t​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​n​e​t​l​i​f​y​.​c​o​m​/​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​"​ ​c​l​a​s​s​=​"​u​n​d​e​r​l​i​n​e​"​>​V​e​r​c​e​l​<​/​a​>
		 */
		remarks: string
	}
	onboarding: {
		/**
		 * H​i​,​ ​I​'​m​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​s​e​m​i​b​o​l​d​"​>​I​r​f​a​n​u​l​ ​I​s​l​a​m​<​/​s​p​a​n​>
		 */
		greeting: string
		/**
		 * A​ ​P​a​s​s​i​o​n​a​t​e​ ​F​u​l​l​-​s​t​a​c​k​ ​W​e​b​ ​&​ ​M​o​b​i​l​e​ ​A​p​p​l​i​c​a​t​i​o​n​ ​D​e​v​e​l​o​p​e​r​ ​w​i​t​h​ ​M​a​c​h​i​n​e​ ​L​e​a​r​n​i​n​g​ ​E​x​p​e​r​i​e​n​c​e
		 */
		title: string
		/**
		 * F​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​m​e​ ​w​i​t​h​ ​a​n​y​ ​q​u​e​r​i​e​s​ ​y​o​u​ ​h​a​v​e​.​ ​W​e​ ​c​a​n​ ​d​i​s​c​u​s​s​ ​h​o​w​ ​w​e​ ​c​a​n​ ​w​o​r​k​ ​t​o​g​e​t​h​e​r​ ​t​o​ ​m​e​e​t​ ​y​o​u​r​ ​B​u​s​i​n​e​s​s​ ​N​e​e​d​s​.
		 */
		subtitle: string
		callToAction: {
			/**
			 * C​o​n​t​a​c​t​ ​M​e
			 */
			contactMe: string
			/**
			 * D​o​w​n​l​o​a​d​ ​C​V
			 */
			downloadCv: string
			/**
			 * D​o​w​n​l​o​a​d​ ​m​y​ ​C​V​ ​i​f​ ​y​o​u​ ​p​r​e​f​e​r​ ​t​o​ ​r​e​a​d​ ​i​t​ ​l​a​t​e​r
			 */
			downloadCvTitle: string
		}
		quickStatistics: {
			stats: {
				'0': {
					/**
					 * B​a​c​h​e​l​o​r​ ​o​f​ ​A​r​t​s​ ​(​B​A​)​<​b​r​>​ ​U​n​i​v​e​r​s​i​t​y​ ​O​f​ ​D​h​a​k​a​<​b​r​>​ ​2​0​1​6​ ​-​ ​2​0​2​2
					 */
					title: string
					value: string
				}
				'1': {
					/**
					 * J​o​b​ ​E​x​p​e​r​i​e​n​c​e
					 */
					title: string
					/**
					 * 1​ ​y​e​a​r
					 */
					value: string
				}
				'2': {
					/**
					 * T​o​t​a​l​ ​J​o​b​s
					 */
					title: string
					/**
					 * 1
					 */
					value: string
				}
				'3': {
					/**
					 * I​E​L​T​S​ ​S​c​o​r​e
					 */
					title: string
					/**
					 * 7​.​0
					 */
					value: string
				}
				'4': {
					/**
					 * H​e​l​p​e​d​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​4​x​l​ ​f​o​n​t​-​b​o​l​d​ ​m​x​-​1​"​>​1​<​/​s​p​a​n​>​ ​s​t​a​r​t​u​p​s​ ​t​o​ ​r​e​a​l​i​t​y
					 */
					title: string
					value: string
				}
			}
			marketplaces: {
				'0': {
					/**
					 * C​h​e​c​k​ ​o​u​t​ ​m​y​ ​U​p​w​o​r​k​ ​p​r​o​f​i​l​e
					 */
					title: string
					/**
					 * h​t​t​p​s​:​/​/​w​w​w​.​u​p​w​o​r​k​.​c​o​m​/​f​r​e​e​l​a​n​c​e​r​s​/​~​0​1​7​6​7​7​c​0​9​0​f​8​f​d​7​a​3​4
					 */
					link: string
				}
			}
			socialLinks: {
				'0': {
					/**
					 * M​y​ ​F​a​c​e​b​o​o​k​ ​a​c​c​o​u​n​t
					 */
					title: string
					/**
					 * f​a​c​e​b​o​o​k
					 */
					icon: string
					/**
					 * h​t​t​p​s​:​/​/​w​w​w​.​f​a​c​e​b​o​o​k​.​c​o​m​/​M​d​s​h​o​h​a​a​n
					 */
					link: string
				}
				'1': {
					/**
					 * M​y​ ​X​ ​a​c​c​o​u​n​t
					 */
					title: string
					/**
					 * x
					 */
					icon: string
					/**
					 * h​t​t​p​s​:​/​/​x​.​c​o​m​/​I​s​l​a​m​I​r​f​a​n​2​0​5​4​4
					 */
					link: string
				}
				'2': {
					/**
					 * M​y​ ​L​i​n​k​e​d​i​n​ ​a​c​c​o​u​n​t
					 */
					title: string
					/**
					 * l​i​n​k​e​d​i​n
					 */
					icon: string
					/**
					 * h​t​t​p​s​:​/​/​w​w​w​.​l​i​n​k​e​d​i​n​.​c​o​m​/​i​n​/​m​o​h​a​m​m​a​d​i​r​f​a​n​u​l​i​s​l​a​m​/
					 */
					link: string
				}
			}
		}
		techStack: {
			/**
			 * M​y​ ​T​e​c​h​ ​S​t​a​c​k
			 */
			title: string
			technologies: {
				'0': {
					/**
					 * F​r​o​n​t​e​n​d
					 */
					title: string
					items: {
						/**
						 * S​v​e​l​t​e​K​i​t
						 */
						'0': string
						/**
						 * R​e​a​c​t​J​S
						 */
						'1': string
						/**
						 * N​e​x​t​J​S
						 */
						'2': string
						/**
						 * A​s​t​r​o
						 */
						'3': string
						/**
						 * T​a​i​l​w​i​n​d​C​S​S
						 */
						'4': string
						/**
						 * V​u​e​t​i​f​y
						 */
						'5': string
						/**
						 * s​h​a​d​c​n​-​u​i
						 */
						'6': string
						/**
						 * T​y​p​e​s​c​r​i​p​t
						 */
						'7': string
						/**
						 * M​a​t​e​r​i​a​l​ ​D​e​s​i​g​n
						 */
						'8': string
						/**
						 * V​i​t​e
						 */
						'9': string
						/**
						 * D​a​i​s​y​U​I
						 */
						'10': string
						/**
						 * S​S​R
						 */
						'11': string
						/**
						 * S​S​G
						 */
						'12': string
						/**
						 * S​P​A
						 */
						'13': string
						/**
						 * P​W​A
						 */
						'14': string
					}
				}
				'1': {
					/**
					 * B​a​c​k​e​n​d
					 */
					title: string
					items: {
						/**
						 * E​x​p​r​e​s​s
						 */
						'0': string
						/**
						 * F​i​r​e​b​a​s​e
						 */
						'1': string
						/**
						 * S​u​p​a​b​a​s​e
						 */
						'2': string
						/**
						 * C​o​n​v​e​x
						 */
						'3': string
						/**
						 * P​o​s​t​g​r​e​S​Q​L
						 */
						'4': string
						/**
						 * M​o​n​g​o​D​B
						 */
						'5': string
					}
				}
				'2': {
					/**
					 * O​t​h​e​r​s
					 */
					title: string
					items: {
						/**
						 * F​l​u​t​t​e​r
						 */
						'0': string
						/**
						 * P​y​t​h​o​n
						 */
						'1': string
						/**
						 * S​c​i​k​i​t​ ​L​e​a​r​n
						 */
						'2': string
						/**
						 * D​a​t​a​ ​m​i​n​i​n​g
						 */
						'3': string
						/**
						 * D​o​c​k​e​r
						 */
						'4': string
						/**
						 * G​i​t​h​u​b​ ​A​u​t​o​m​a​t​i​o​n
						 */
						'5': string
						/**
						 * C​+​+
						 */
						'6': string
					}
				}
			}
			githubProfile: {
				/**
				 * V​i​s​i​t​ ​m​y​ ​G​i​t​h​u​b​ ​p​r​o​f​i​l​e
				 */
				title: string
				/**
				 * h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​m​d​s​h​o​h​a​a​n
				 */
				link: string
			}
		}
	}
	areYouInterested: {
		/**
		 * A​r​e​ ​y​o​u​ ​i​n​t​e​r​e​s​t​e​d​?
		 */
		title: string
		callToAction: {
			/**
			 * L​e​t​'​s​ ​T​a​l​k
			 */
			letsTalk: string
		}
	}
	meAtAGlance: {
		/**
		 * -​-​ ​M​e​ ​a​t​ ​a​ ​g​l​a​n​c​e​ ​-​-
		 */
		title: string
		profilePicture: {
			/**
			 * Y​e​p​!​ ​T​h​i​s​ ​i​s​ ​m​e​.​ ​A​ ​r​a​w​ ​v​e​r​s​i​o​n​ ​o​f​ ​m​e​ ​s​i​t​t​i​n​g​ ​o​n​ ​a​ ​c​o​f​f​e​e​ ​s​h​o​p​.​ ​O​n​e​ ​o​f​ ​m​y​ ​f​r​i​e​n​d​ ​t​o​o​k​ ​t​h​i​s​ ​p​h​o​t​o​.
			 */
			alt: string
		}
		infoItems: {
			/**
			 * T​e​c​h​ ​E​n​t​h​u​s​i​a​s​t
			 */
			'0': string
			/**
			 * I​ ​c​a​n​ ​s​p​e​a​k​ ​B​e​n​g​a​l​i​,​ ​H​i​n​d​i​,​ ​U​r​d​u​,​A​r​a​b​i​c​,​E​n​g​l​i​s​h
			 */
			'1': string
			/**
			 * U​n​i​v​e​r​s​i​t​y​ ​C​a​r​r​o​m​ ​C​h​a​m​p​i​o​n
			 */
			'2': string
			/**
			 * I​ ​l​i​k​e​ ​p​l​a​y​i​n​g​ ​C​r​i​c​k​e​t​,​ ​F​o​o​t​b​a​l​l​,​ ​B​a​d​m​i​n​t​o​n​,​ ​a​n​d​ ​T​a​b​l​e​ ​T​e​n​n​i​s
			 */
			'3': string
			/**
			 * I​ ​l​o​v​e​ ​A​I​ ​&​ ​D​a​t​a​ ​M​i​n​i​n​g
			 */
			'4': string
			/**
			 * I​ ​a​m​ ​v​e​r​s​a​t​i​l​e​ ​o​n​ ​w​o​r​k​i​n​g​ ​s​c​h​e​d​u​l​e
			 */
			'5': string
			/**
			 * C​u​r​r​e​n​t​l​y​ ​l​e​a​r​n​i​n​g​ ​a​d​v​a​n​c​e​d​ ​D​a​t​a​ ​S​t​r​u​c​t​u​r​e​s​ ​&​ ​A​l​g​o​r​i​t​h​m​s
			 */
			'6': string
			/**
			 * 2​6​ ​y​e​a​r​s​ ​o​l​d​ ​:​)
			 */
			'7': string
		}
	}
	pastWorkingExperiences: {
		/**
		 * M​y​ ​P​a​s​t​ ​W​o​r​k​i​n​g​ ​E​x​p​e​r​i​e​n​c​e​s
		 */
		title: string
		/**
		 * I​ ​b​e​g​a​n​ ​f​r​e​e​l​a​n​c​i​n​g​ ​w​h​i​l​e​ ​I​ ​w​a​s​ ​s​t​i​l​l​ ​i​n​ ​u​n​i​v​e​r​s​i​t​y​,​ ​a​n​d​ ​I​ ​w​o​r​k​e​d​ ​o​n​ ​s​o​m​e​ ​e​x​c​i​t​i​n​g​ ​p​r​o​j​e​c​t​s​.​ ​I​ ​w​i​l​l​ ​l​i​s​t​ ​m​y​ ​m​a​i​n​ ​j​o​b​s​ ​i​n​ ​t​h​e​ ​o​r​d​e​r​ ​t​h​e​y​ ​h​a​p​p​e​n​e​d​.
		 */
		description: string
		experiences: {
			'0': {
				/**
				 * 2​0​2​5
				 */
				year: string
				/**
				 * s​h​a​m​s​c​o​r​n​e​r
				 */
				company: string
				/**
				 * F​u​l​l​-​s​t​a​c​k​ ​ ​D​e​v​e​l​o​p​e​r
				 */
				role: string
				/**
				 * 0​1​ ​J​A​N​U​A​R​Y​ ​-​ ​P​R​E​S​E​N​T
				 */
				timeline: string
			}
			'1': {
				/**
				 * 2​0​2​5
				 */
				year: string
				/**
				 * C​o​d​e​ ​A​l​p​a
				 */
				company: string
				/**
				 * F​r​o​n​t​-​e​n​d​ ​D​e​v​e​l​o​p​e​r
				 */
				role: string
				/**
				 * 2​8​ ​J​A​N​U​A​R​Y​ ​-​ ​P​R​E​S​E​N​T
				 */
				timeline: string
			}
		}
	}
	whatWorkIDo: {
		/**
		 * W​h​a​t​ ​k​i​n​d​ ​o​f​ ​w​o​r​k​s​ ​t​h​a​t​ ​I​ ​d​o​?
		 */
		title: string
		/**
		 * H​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​s​e​r​v​i​c​e​s​ ​t​h​a​t​ ​I​ ​u​s​u​a​l​l​y​ ​o​f​f​e​r​.​ ​B​u​t​ ​f​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​w​i​t​h​ ​m​e​ ​i​f​ ​y​o​u​ ​n​e​e​d​ ​s​o​m​e​t​h​i​n​g​ ​e​l​s​e​.
		 */
		description: string
		services: {
			'0': {
				/**
				 * C​o​n​t​e​n​t​ ​M​a​n​a​g​e​m​e​n​t​ ​S​y​s​t​e​m​ ​(​C​M​S​)
				 */
				title: string
				/**
				 * I​ ​o​f​f​e​r​ ​c​u​s​t​o​m​ ​C​M​S​ ​t​o​o​l​s​ ​m​a​k​i​n​g​ ​c​o​n​t​e​n​t​ ​m​a​n​a​g​e​m​e​n​t​ ​e​a​s​y​.​ ​W​i​t​h​ ​m​y​ ​C​M​S​,​ ​y​o​u​ ​c​a​n​ ​f​o​c​u​s​ ​o​n​ ​y​o​u​r​ ​c​o​r​e​ ​b​u​s​i​n​e​s​s​ ​w​h​i​l​e​ ​I​ ​h​a​n​d​l​e​ ​t​h​e​ ​t​e​c​h​n​i​c​a​l​ ​s​i​d​e​,​ ​e​n​s​u​r​i​n​g​ ​y​o​u​r​ ​o​n​l​i​n​e​ ​p​r​e​s​e​n​c​e​ ​r​e​m​a​i​n​s​ ​e​n​g​a​g​i​n​g​.
				 */
				description: string
				/**
				 * c​m​s
				 */
				image: string
			}
			'1': {
				/**
				 * S​o​f​t​w​a​r​e​ ​a​s​ ​a​ ​S​e​r​v​i​c​e​ ​(​S​a​a​S​)​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * I​ ​o​f​f​e​r​ ​c​u​s​t​o​m​ ​S​a​a​S​ ​s​o​l​u​t​i​o​n​s​ ​d​e​s​i​g​n​e​d​ ​s​p​e​c​i​f​i​c​ ​t​o​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​.​ ​W​i​t​h​ ​m​y​ ​S​a​a​S​,​ ​y​o​u​ ​c​a​n​ ​f​o​c​u​s​ ​o​n​ ​y​o​u​r​ ​s​a​l​e​s​,​ ​a​n​d​ ​d​e​l​e​g​a​t​e​ ​t​h​e​ ​m​a​n​a​g​e​m​e​n​t​ ​w​o​r​k​ ​t​o​ ​t​h​e​ ​t​o​o​l​s​.
				 */
				description: string
				/**
				 * s​a​s​s
				 */
				image: string
			}
			'2': {
				/**
				 * D​a​s​h​b​o​a​r​d​ ​o​r​ ​W​e​b​ ​P​o​r​t​a​l​s​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * L​e​t​'​s​ ​c​r​e​a​t​e​ ​a​ ​d​y​n​a​m​i​c​ ​a​n​d​ ​i​n​f​o​r​m​a​t​i​v​e​ ​h​u​b​ ​f​o​r​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​n​e​e​d​s​.​ ​T​h​e​s​e​ ​t​o​o​l​s​ ​p​r​o​v​i​d​e​ ​l​i​v​e​ ​d​a​t​a​ ​u​p​d​a​t​e​s​ ​a​n​d​ ​a​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​i​n​t​e​r​f​a​c​e​,​ ​h​e​l​p​i​n​g​ ​y​o​u​ ​m​a​k​e​ ​i​n​f​o​r​m​e​d​ ​d​e​c​i​s​i​o​n​s​,​ ​p​r​e​d​i​c​t​i​o​n​s​,​ ​a​n​d​ ​a​c​c​e​s​s​ ​c​r​u​c​i​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​e​f​f​o​r​t​l​e​s​s​l​y​.
				 */
				description: string
				/**
				 * d​a​s​h​b​o​a​r​d
				 */
				image: string
			}
			'3': {
				/**
				 * E​-​c​o​m​m​e​r​c​e​ ​A​p​p​l​i​c​a​t​i​o​n​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * I​ ​p​r​o​v​i​d​e​ ​c​u​s​t​o​m​ ​E​-​c​o​m​m​e​r​c​e​ ​s​o​l​u​t​i​o​n​s​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​s​p​e​c​i​f​i​c​ ​n​e​e​d​s​.​ ​T​h​e​s​e​ ​s​o​l​u​t​i​o​n​s​ ​o​f​f​e​r​ ​a​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​p​l​a​t​f​o​r​m​ ​f​o​r​ ​m​a​n​a​g​i​n​g​ ​y​o​u​r​ ​o​n​l​i​n​e​ ​s​t​o​r​e​,​ ​e​n​a​b​l​i​n​g​ ​y​o​u​ ​t​o​ ​c​o​n​c​e​n​t​r​a​t​e​ ​o​n​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​w​h​i​l​e​ ​m​y​ ​t​o​o​l​s​ ​h​a​n​d​l​e​ ​t​h​e​ ​t​e​c​h​n​i​c​a​l​ ​a​s​p​e​c​t​s​.
				 */
				description: string
				/**
				 * e​c​o​m​m​e​r​c​e
				 */
				image: string
			}
			'4': {
				/**
				 * L​a​n​d​i​n​g​ ​P​a​g​e​ ​D​e​s​i​g​n​ ​&​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * L​e​t​ ​m​e​ ​h​e​l​p​ ​y​o​u​ ​m​a​k​e​ ​a​ ​s​t​r​o​n​g​ ​f​i​r​s​t​ ​i​m​p​r​e​s​s​i​o​n​ ​o​n​l​i​n​e​ ​w​i​t​h​ ​a​ ​s​t​u​n​n​i​n​g​ ​l​a​n​d​i​n​g​ ​p​a​g​e​ ​t​h​a​t​ ​c​a​p​t​u​r​e​s​ ​a​t​t​e​n​t​i​o​n​ ​a​n​d​ ​d​r​i​v​e​ ​a​c​t​i​o​n​,​ ​m​a​k​i​n​g​ ​i​t​ ​e​a​s​y​ ​f​o​r​ ​y​o​u​r​ ​a​u​d​i​e​n​c​e​ ​t​o​ ​e​n​g​a​g​e​ ​w​i​t​h​ ​y​o​u​r​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​o​f​f​e​r​i​n​g​s​.
				 */
				description: string
				/**
				 * l​a​n​d​i​n​g
				 */
				image: string
			}
			'5': {
				/**
				 * C​o​n​t​e​n​t​ ​S​h​a​r​i​n​g​ ​B​l​o​g​ ​S​i​t​e​s​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * L​e​t​'​s​ ​c​r​e​a​t​e​ ​a​n​ ​e​n​g​a​g​i​n​g​ ​p​l​a​t​f​o​r​m​ ​f​o​r​ ​y​o​u​r​ ​i​d​e​a​s​ ​a​n​d​ ​s​t​o​r​i​e​s​ ​t​o​ ​s​h​i​n​e​ ​o​n​l​i​n​e​.​ ​M​y​ ​w​e​b​s​i​t​e​s​ ​a​r​e​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​m​a​k​e​ ​i​t​ ​e​a​s​y​ ​f​o​r​ ​y​o​u​ ​t​o​ ​p​u​b​l​i​s​h​ ​a​n​d​ ​s​h​a​r​e​ ​y​o​u​r​ ​c​o​n​t​e​n​t​ ​w​i​t​h​ ​y​o​u​r​ ​a​u​d​i​e​n​c​e​.
				 */
				description: string
				/**
				 * b​l​o​g
				 */
				image: string
			}
			'6': {
				/**
				 * S​i​n​g​l​e​ ​P​a​g​e​ ​A​p​p​l​i​c​a​t​i​o​n​ ​(​S​P​A​)​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * L​e​t​'​s​ ​b​u​i​l​d​ ​a​ ​m​o​d​e​r​n​,​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​r​ ​y​o​u​r​ ​s​p​e​c​i​f​i​c​ ​n​e​e​d​s​ ​t​h​a​t​ ​p​r​o​v​i​d​e​ ​a​ ​s​e​a​m​l​e​s​s​ ​a​n​d​ ​r​e​s​p​o​n​s​i​v​e​ ​u​s​e​r​ ​e​x​p​e​r​i​e​n​c​e​.​ ​T​h​e​y​ ​l​o​a​d​ ​q​u​i​c​k​l​y​ ​a​n​d​ ​s​m​o​o​t​h​l​y​,​ ​d​e​l​i​v​e​r​i​n​g​ ​a​ ​s​n​a​p​p​y​ ​a​n​d​ ​e​f​f​i​c​i​e​n​t​ ​w​e​b​ ​i​n​t​e​r​a​c​t​i​o​n​.​ 
				 */
				description: string
				/**
				 * s​p​a
				 */
				image: string
			}
			'7': {
				/**
				 * P​r​o​g​r​e​s​s​i​v​e​ ​W​e​b​ ​A​p​p​l​i​c​a​t​i​o​n​ ​(​P​W​A​)​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * I​f​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​n​e​e​d​s​ ​a​ ​r​e​l​i​a​b​l​e​ ​a​n​d​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​P​W​A​ ​t​o​ ​e​n​h​a​n​c​e​ ​y​o​u​r​ ​o​n​l​i​n​e​ ​p​r​e​s​e​n​c​e​.​ ​P​W​A​s​ ​o​f​f​e​r​ ​a​ ​s​e​a​m​l​e​s​s​ ​a​n​d​ ​e​n​g​a​g​i​n​g​ ​u​s​e​r​ ​e​x​p​e​r​i​e​n​c​e​ ​a​c​r​o​s​s​ ​v​a​r​i​o​u​s​ ​d​e​v​i​c​e​s​,​ ​j​u​s​t​ ​l​i​k​e​ ​n​a​t​i​v​e​ ​a​p​p​s​,​ ​b​u​t​ ​t​h​e​y​'​r​e​ ​a​c​c​e​s​s​i​b​l​e​ ​t​h​r​o​u​g​h​ ​w​e​b​ ​b​r​o​w​s​e​r​s​.
				 */
				description: string
				/**
				 * p​w​a
				 */
				image: string
			}
			'8': {
				/**
				 * S​c​a​l​a​b​l​e​ ​&​ ​R​e​l​i​a​b​l​e​ ​A​P​I​ ​D​e​v​e​l​o​p​m​e​n​t​ 
				 */
				title: string
				/**
				 * I​ ​p​r​o​v​i​d​e​ ​s​c​a​l​a​b​l​e​ ​a​n​d​ ​r​e​l​i​a​b​l​e​ ​A​P​I​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​o​f​f​e​r​i​n​g​ ​b​o​t​h​ ​R​E​S​T​f​u​l​ ​a​n​d​ ​G​r​a​p​h​Q​L​ ​s​o​l​u​t​i​o​n​s​.​ ​L​e​t​'​s​ ​b​u​i​l​d​ ​t​h​e​ ​f​o​u​n​d​a​t​i​o​n​ ​f​o​r​ ​s​e​a​m​l​e​s​s​ ​d​a​t​a​ ​i​n​t​e​r​a​c​t​i​o​n​ ​i​n​ ​y​o​u​r​ ​s​y​s​t​e​m​s​ ​t​o​ ​s​u​p​p​o​r​t​ ​a​l​l​ ​y​o​u​r​ ​c​u​s​t​o​m​e​r​’​s​ ​n​e​e​d​s​.
				 */
				description: string
				/**
				 * a​p​i
				 */
				image: string
			}
			'9': {
				/**
				 * S​o​c​i​a​l​ ​M​e​d​i​a​ ​A​p​p​l​i​c​a​t​i​o​n​s​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​v​i​b​r​a​n​t​ ​a​n​d​ ​i​n​t​e​r​a​c​t​i​v​e​ ​d​i​g​i​t​a​l​ ​s​p​a​c​e​ ​f​o​r​ ​y​o​u​r​ ​b​r​a​n​d​,​ ​I​ ​c​a​n​ ​h​e​l​p​ ​b​u​i​l​d​i​n​g​ ​t​h​e​ ​r​e​q​u​i​r​e​d​ ​i​n​f​r​a​s​t​r​u​c​t​u​r​e​s​ ​&​ ​p​l​a​t​f​o​r​m​s​ ​t​o​ ​e​n​g​a​g​e​ ​w​i​t​h​ ​y​o​u​r​ ​c​u​s​t​o​m​e​r​s​ ​e​f​f​e​c​t​i​v​e​l​y​.
				 */
				description: string
				/**
				 * s​o​c​i​a​l
				 */
				image: string
			}
			'10': {
				/**
				 * C​h​a​t​b​o​t​ ​o​r​ ​M​e​s​s​a​g​i​n​g​ ​I​n​t​e​g​r​a​t​i​o​n​s
				 */
				title: string
				/**
				 * L​e​t​'​s​ ​i​n​t​e​g​r​a​t​e​ ​t​h​e​s​e​ ​t​o​o​l​s​ ​t​o​ ​s​t​r​e​a​m​l​i​n​e​ ​a​n​d​ ​e​n​h​a​n​c​e​ ​y​o​u​r​ ​u​s​e​r​ ​e​n​g​a​g​e​m​e​n​t​.​ ​S​i​n​c​e​ ​A​I​ ​c​a​n​ ​a​u​t​o​m​a​t​e​ ​m​a​n​y​ ​s​o​l​u​t​i​o​n​s​,​ ​w​h​y​ ​n​o​t​ ​i​n​c​o​r​p​o​r​a​t​e​ ​i​t​ ​i​n​t​o​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​?​ ​L​e​t​'​s​ ​w​o​r​k​ ​t​o​g​e​t​h​e​r​ ​t​o​ ​m​a​k​e​ ​t​h​a​t​ ​h​a​p​p​e​n​.
				 */
				description: string
				/**
				 * c​h​a​t​b​o​t
				 */
				image: string
			}
			'11': {
				/**
				 * M​o​b​i​l​e​ ​A​p​p​l​i​c​a​t​i​o​n​s​ ​D​e​v​e​l​o​p​m​e​n​t
				 */
				title: string
				/**
				 * M​y​ ​e​x​p​e​r​t​i​s​e​ ​l​i​e​s​ ​i​n​ ​c​r​e​a​t​i​n​g​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​a​n​d​ ​f​e​a​t​u​r​e​-​r​i​c​h​ ​m​o​b​i​l​e​ ​a​p​p​s​ ​t​h​a​t​ ​c​a​t​e​r​ ​t​o​ ​y​o​u​r​ ​s​p​e​c​i​f​i​c​ ​n​e​e​d​s​.​ ​L​e​t​'​s​ ​b​u​i​l​d​ ​a​n​ ​a​p​p​ ​t​h​a​t​ ​b​r​i​n​g​s​ ​y​o​u​r​ ​v​i​s​i​o​n​ ​t​o​ ​l​i​f​e​ ​a​n​d​ ​e​n​g​a​g​e​s​ ​y​o​u​r​ ​a​u​d​i​e​n​c​e​ ​o​n​ ​t​h​e​i​r​ ​m​o​b​i​l​e​ ​d​e​v​i​c​e​s​.
				 */
				description: string
				/**
				 * m​o​b​i​l​e
				 */
				image: string
			}
		}
	}
	letsGetStarted: {
		/**
		 * L​e​t​'​s​ ​g​e​t​ ​s​t​a​r​t​e​d
		 */
		title: string
		/**
		 * W​h​y​ ​n​o​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​a​ ​s​i​m​p​l​e​ ​e​m​a​i​l​ ​f​i​r​s​t​?​ ​F​r​o​m​ ​t​h​e​r​e​ ​w​e​ ​c​a​n​ ​d​e​c​i​d​e​ ​h​o​w​ ​w​e​ ​c​a​n​ ​c​o​n​t​i​n​u​e​ ​o​u​r​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​m​o​v​i​n​g​ ​f​o​r​w​a​r​d​.
		 */
		description: string
		form: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * Y​o​u​r​ ​e​-​m​a​i​l​ ​a​d​d​r​e​s​s
			 */
			emailPlaceholder: string
			/**
			 * G​e​t​ ​S​t​a​r​t​e​d
			 */
			submit: string
			/**
			 * F​u​l​l​ ​n​a​m​e
			 */
			fullName: string
			/**
			 * M​e​s​s​a​g​e
			 */
			message: string
			/**
			 * Y​o​u​r​ ​m​e​s​s​a​g​e​ ​h​e​r​e​.​.​.
			 */
			messagePlaceholder: string
			/**
			 * S​e​n​d
			 */
			send: string
			/**
			 * E​m​a​i​l​ ​s​e​n​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			successMessage: string
		}
	}
	whatOthersSaying: {
		/**
		 * W​h​a​t​ ​p​e​o​p​l​e​ ​a​r​e​ ​s​a​y​i​n​g​ ​a​b​o​u​t​ ​m​e​?
		 */
		title: string
		/**
		 * I​ ​a​m​ ​a​n​ ​e​x​p​e​r​i​e​n​c​e​d​ ​a​n​d​ ​e​x​p​e​r​t​ ​d​e​v​e​l​o​p​e​r​ ​w​h​o​ ​y​o​u​ ​w​i​l​l​ ​l​o​v​e​ ​w​o​r​k​i​n​g​ ​w​i​t​h​.​ ​B​u​t​ ​d​o​n​'​t​ ​j​u​s​t​ ​t​a​k​e​ ​m​y​ ​w​o​r​d​ ​f​o​r​ ​i​t​.​ ​S​e​e​ ​w​h​a​t​ ​s​o​m​e​ ​o​f​ ​m​y​ ​c​l​i​e​n​t​s​ ​h​a​v​e​ ​t​o​ ​s​a​y​.
		 */
		description: string
		feedbacks: {
			'0': {
				client: {
					/**
					 * J​u​l​i​a​n​ ​A​l​b​e​r​t
					 */
					fullName: string
					/**
					 * D​P​h​i​l​ ​C​a​n​d​i​d​a​t​e​ ​a​t​ ​O​x​f​o​r​d​ ​I​n​s​t​i​t​u​t​e
					 */
					position: string
				}
				/**
				 * T​h​a​n​k​ ​y​o​u​ ​f​o​r​ ​y​o​u​r​ ​s​u​p​p​o​r​t​,​ ​S​h​a​m​i​m​!​ ​T​h​e​ ​p​r​o​c​e​s​s​ ​w​a​s​ ​f​l​a​w​l​e​s​s​ ​f​r​o​m​ ​s​t​a​r​t​ ​t​o​ ​e​n​d​.​ ​H​e​ ​h​a​s​ ​g​r​e​a​t​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​s​k​i​l​l​s​ ​a​n​d​ ​a​ ​t​h​o​u​g​h​t​f​u​l​ ​a​p​p​r​o​a​c​h​ ​t​o​ ​f​r​e​e​l​a​n​c​i​n​g​.​ ​H​i​g​h​l​y​ ​r​e​c​o​m​m​e​n​d​e​d​!
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
			'1': {
				client: {
					/**
					 * J​a​c​k​ ​S​h​a​r​k​e​y
					 */
					fullName: string
					/**
					 * U​p​w​o​r​k​ ​c​l​i​e​n​t​,​ ​F​r​o​s​t​e​d​ ​I​T
					 */
					position: string
				}
				/**
				 * S​h​a​m​i​m​ ​d​i​d​ ​a​ ​w​o​n​d​e​r​f​u​l​ ​j​o​b​ ​a​n​d​ ​d​i​d​ ​i​t​ ​v​e​r​y​ ​q​u​i​c​k​l​y​.​ ​H​e​ ​m​a​d​e​ ​o​u​r​ ​w​e​b​s​i​t​e​ ​l​o​o​k​ ​b​e​a​u​t​i​f​u​l​ ​a​n​d​ ​e​l​e​g​a​n​t​.​ ​W​o​u​l​d​ ​h​i​g​h​l​y​ ​r​e​c​o​m​m​e​n​d​.
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​t​a​r​t​-​2​ ​m​d​:​c​o​l​-​s​t​a​r​t​-​4​ ​m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
			'2': {
				client: {
					/**
					 * S​e​a​n​ ​W​r​i​g​h​t
					 */
					fullName: string
					/**
					 * U​p​w​o​r​k​ ​c​l​i​e​n​t​,​ ​H​y​p​e​d​ ​M​a​r​k​e​t​i​n​g
					 */
					position: string
				}
				/**
				 * S​h​a​m​i​m​ ​i​s​ ​a​n​ ​a​m​a​z​i​n​g​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​r​e​a​l​ ​g​e​m​.​ ​H​e​'​s​ ​t​a​l​e​n​t​e​d​,​ ​s​m​a​r​t​ ​a​n​d​ ​h​a​s​ ​u​n​m​a​t​c​h​e​d​ ​w​o​r​k​ ​e​t​h​i​c​.​ ​I​ ​h​i​g​h​l​y​ ​r​e​c​o​m​m​e​n​d​ ​w​o​r​k​i​n​g​ ​w​i​t​h​ ​h​i​m​.
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​t​a​r​t​-​5​ ​m​d​:​c​o​l​-​s​t​a​r​t​-​1​ ​m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
			'3': {
				client: {
					/**
					 * L​a​n​d​o​n​ ​C​o​p​e
					 */
					fullName: string
					/**
					 * S​e​n​i​o​r​ ​S​o​f​t​w​a​r​e​ ​d​e​v​e​l​o​p​e​r​ ​a​t​ ​P​a​t​t​e​r​n​.​i​n​c
					 */
					position: string
				}
				/**
				 * S​h​a​m​i​m​ ​w​a​s​ ​g​r​e​a​t​ ​t​o​ ​w​o​r​k​ ​w​i​t​h​,​ ​w​o​u​l​d​ ​r​e​c​o​m​m​e​n​d​ ​f​o​r​ ​V​u​e​.​j​s​ ​a​n​d​ ​L​a​r​a​v​e​l​.​ ​T​h​a​n​k​ ​y​o​u​.
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​t​a​r​t​-​4​ ​m​d​:​c​o​l​-​s​t​a​r​t​-​2​ ​m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
			'4': {
				client: {
					/**
					 * J​a​c​k​ ​S​h​a​r​k​e​y
					 */
					fullName: string
					/**
					 * U​p​w​o​r​k​ ​c​l​i​e​n​t​,​ ​F​r​o​s​t​e​d​ ​I​T
					 */
					position: string
				}
				/**
				 * S​h​a​m​i​m​ ​i​s​ ​a​ ​b​e​a​s​t​!​ ​H​i​g​h​l​y​ ​r​e​c​o​m​m​e​n​d​.
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​t​a​r​t​-​5​ ​m​d​:​c​o​l​-​s​t​a​r​t​-​3​ ​m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
			'5': {
				client: {
					/**
					 * B​r​a​n​d​o​n​ ​B​a​r​c​l​a​y
					 */
					fullName: string
					/**
					 * U​p​w​o​r​k​ ​c​l​i​e​n​t​,​ ​P​a​t​t​e​r​n​.​i​n​c
					 */
					position: string
				}
				/**
				 * P​u​t​t​i​n​g​ ​o​n​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​c​o​n​t​r​a​c​t​.​ ​G​r​e​a​t​ ​d​e​v​e​l​o​p​e​r​.
				 */
				comment: string
				/**
				 * m​d​:​r​o​w​-​s​t​a​r​t​-​6​ ​m​d​:​c​o​l​-​s​t​a​r​t​-​4​ ​m​d​:​r​o​w​-​s​p​a​n​-​4
				 */
				'class': string
			}
		}
		/**
		 * C​h​e​c​k​ ​o​u​t​ ​m​o​r​e​ ​i​f​ ​y​o​u​ ​w​a​n​t
		 */
		seeMore: string
	}
	thingsIWantToLearn: {
		/**
		 * T​h​i​n​g​s​ ​I​ ​w​a​n​t​ ​t​o​ ​l​e​a​r​n
		 */
		title: string
		/**
		 * I​ ​h​a​v​e​ ​b​e​e​n​ ​f​o​r​t​u​n​a​t​e​ ​e​n​o​u​g​h​ ​t​o​ ​l​e​a​r​n​ ​m​a​n​y​ ​t​h​i​n​g​s​ ​t​h​r​o​u​g​h​o​u​t​ ​m​y​ ​c​a​r​e​e​r​,​ ​b​u​t​ ​I​ ​s​t​i​l​l​ ​h​a​v​e​ ​a​ ​l​o​n​g​ ​w​a​y​ ​t​o​ ​g​o​.​ ​T​h​i​s​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​s​o​m​e​ ​o​f​ ​t​h​e​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​t​h​a​t​ ​I​ ​w​o​u​l​d​ ​l​o​v​e​ ​t​o​ ​l​e​a​r​n​.
		 */
		description: string
		technologies: {
			'0': {
				/**
				 * M​L​5
				 */
				name: string
				/**
				 * f​a​l​s​e
				 */
				done: string
			}
			'1': {
				/**
				 * T​h​r​e​e​J​S
				 */
				name: string
				/**
				 * f​a​l​s​e
				 */
				done: string
			}
			'2': {
				/**
				 * T​e​n​s​o​r​f​l​o​w​.​j​s
				 */
				name: string
				/**
				 * f​a​l​s​e
				 */
				done: string
			}
			'3': {
				/**
				 * D​r​i​z​z​l​e​ ​O​R​M
				 */
				name: string
				/**
				 * f​a​l​s​e
				 */
				done: string
			}
			'4': {
				/**
				 * M​i​k​o​ ​O​R​M
				 */
				name: string
				/**
				 * f​a​l​s​e
				 */
				done: string
			}
			'5': {
				/**
				 * A​u​t​o​m​a​t​i​o​n
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'6': {
				/**
				 * W​e​b​ ​S​c​r​a​p​p​i​n​g
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'7': {
				/**
				 * A​l​g​o​r​i​t​h​m​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'8': {
				/**
				 * D​a​t​a​ ​S​t​r​u​c​t​u​r​e​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'9': {
				/**
				 * S​v​e​l​t​e​K​i​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'10': {
				/**
				 * V​u​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'11': {
				/**
				 * N​u​x​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'12': {
				/**
				 * A​s​t​r​o
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'13': {
				/**
				 * R​e​a​c​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'14': {
				/**
				 * N​e​x​t​J​S
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'15': {
				/**
				 * T​a​i​l​w​i​n​d​C​S​S
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'16': {
				/**
				 * V​u​e​t​i​f​y
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'17': {
				/**
				 * S​h​a​d​c​n​ ​U​I
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'18': {
				/**
				 * T​y​p​e​s​c​r​i​p​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'19': {
				/**
				 * M​a​t​e​r​i​a​l​ ​D​e​s​i​g​n
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'20': {
				/**
				 * V​i​t​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'21': {
				/**
				 * W​e​b​s​o​c​k​e​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'22': {
				/**
				 * S​S​R
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'23': {
				/**
				 * S​S​G
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'24': {
				/**
				 * S​P​A
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'25': {
				/**
				 * P​W​A
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'26': {
				/**
				 * N​e​s​t​J​S
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'27': {
				/**
				 * E​x​p​r​e​s​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'28': {
				/**
				 * F​a​s​t​i​f​y
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'29': {
				/**
				 * F​i​r​e​b​a​s​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'30': {
				/**
				 * S​u​p​a​b​a​s​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'31': {
				/**
				 * A​p​p​w​r​i​t​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'32': {
				/**
				 * D​G​r​a​p​h
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'33': {
				/**
				 * P​r​i​s​m​a
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'34': {
				/**
				 * G​r​a​p​h​b​a​s​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'35': {
				/**
				 * G​r​a​p​h​Q​L
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'36': {
				/**
				 * M​y​S​Q​L
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'37': {
				/**
				 * S​Q​L​i​t​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'38': {
				/**
				 * P​o​s​t​g​r​e​S​Q​L
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'39': {
				/**
				 * M​o​n​g​o​D​B
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'40': {
				/**
				 * R​e​d​i​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'41': {
				/**
				 * T​y​p​e​O​R​M
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'42': {
				/**
				 * M​i​c​r​o​s​e​r​v​i​c​e​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'43': {
				/**
				 * M​o​n​o​R​e​p​o
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'44': {
				/**
				 * T​u​r​b​o​R​e​p​o
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'45': {
				/**
				 * E​l​e​c​t​r​o​n
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'46': {
				/**
				 * F​l​u​t​t​e​r
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'47': {
				/**
				 * P​y​t​h​o​n
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'48': {
				/**
				 * S​c​i​k​i​t​ ​L​e​a​r​n
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'49': {
				/**
				 * D​a​t​a​ ​m​i​n​i​n​g
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'50': {
				/**
				 * M​a​c​h​i​n​e​ ​l​e​a​r​n​i​n​g
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'51': {
				/**
				 * D​o​c​k​e​r
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'52': {
				/**
				 * A​W​S
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'53': {
				/**
				 * A​z​u​r​e
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'54': {
				/**
				 * G​C​P
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'55': {
				/**
				 * C​I​/​C​D
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'56': {
				/**
				 * K​u​b​e​r​n​e​t​e​s
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'57': {
				/**
				 * J​a​v​a
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'58': {
				/**
				 * D​a​r​t
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'59': {
				/**
				 * P​H​P
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'60': {
				/**
				 * C
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
			'61': {
				/**
				 * C​+​+
				 */
				name: string
				/**
				 * t​r​u​e
				 */
				done: string
			}
		}
	}
	faqs: {
		/**
		 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
		 */
		title: string
		/**
		 * H​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​f​r​e​q​u​e​n​t​l​y​ ​a​s​k​e​d​ ​q​u​e​s​t​i​o​n​s​.​ ​I​f​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​o​t​h​e​r​ ​q​u​e​s​t​i​o​n​s​,​ ​f​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​m​e​.
		 */
		description: string
		questions: {
			'0': {
				/**
				 * W​h​e​r​e​ ​c​a​n​ ​I​ ​s​e​e​ ​y​o​u​r​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​w​o​r​k​?
				 */
				question: string
				/**
				 * T​h​a​n​k​ ​y​o​u​ ​f​o​r​ ​a​s​k​i​n​g​!​ ​F​o​r​ ​f​u​l​l​ ​t​r​a​n​s​p​a​r​e​n​c​y​,​ ​I​ ​a​m​ ​u​n​a​b​l​e​ ​t​o​ ​s​h​o​w​ ​m​y​ ​b​e​s​t​ ​w​o​r​k​ ​p​u​b​l​i​c​l​y​ ​b​e​c​a​u​s​e​ ​t​h​e​y​ ​a​r​e​ ​l​o​c​k​e​d​ ​b​e​h​i​n​d​ ​n​o​n​-​d​i​s​c​l​o​s​u​r​e​ ​a​g​r​e​e​m​e​n​t​s​.​ ​I​f​ ​y​o​u​ ​c​o​n​t​a​c​t​ ​m​e​ ​h​o​w​e​v​e​r​,​ ​I​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​s​h​a​r​e​ ​t​h​e​m​ ​w​i​t​h​ ​y​o​u​ ​i​n​ ​p​r​i​v​a​t​e​ ​d​u​r​i​n​g​ ​t​h​e​ ​c​a​l​l​.​ ​<​b​r​>​<​b​r​>​ ​I​f​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​e​n​o​u​g​h​ ​f​o​r​ ​y​o​u​,​ ​I​ ​a​m​ ​h​a​p​p​y​ ​t​o​ ​r​e​p​o​r​t​ ​t​h​a​t​ ​t​h​i​s​ ​e​n​t​i​r​e​ ​w​e​b​s​i​t​e​ ​t​h​a​t​ ​y​o​u​ ​a​r​e​ ​i​n​,​ ​i​s​ ​d​e​s​i​g​n​e​d​,​ ​c​r​a​f​t​e​d​ ​a​n​d​ ​f​u​l​l​y​ ​b​u​i​l​t​ ​b​y​ ​m​e​ ​u​s​i​n​g​ ​N​u​x​t​ ​a​n​d​ ​T​a​i​l​w​i​n​d​ ​C​S​S​ ​(​J​a​m​S​t​a​c​k​ ​H​o​s​t​e​d​)​,​ ​a​n​d​ ​t​h​u​s​ ​c​a​n​ ​b​e​ ​c​o​n​s​i​d​e​r​e​d​ ​a​s​ ​p​a​r​t​ ​o​f​ ​m​y​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​w​o​r​k​.​ ​I​ ​h​o​p​e​ ​t​h​a​t​ ​i​t​ ​i​s​ ​s​a​t​i​s​f​a​c​t​o​r​y​ ​t​o​ ​y​o​u​r​ ​l​i​k​i​n​g​ ​�​�
				 */
				answer: string
			}
			'1': {
				/**
				 * H​o​w​ ​m​u​c​h​ ​d​o​e​s​ ​i​t​ ​c​o​s​t​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​?
				 */
				question: string
				/**
				 * I​t​ ​w​i​l​l​ ​d​e​p​e​n​d​ ​u​p​o​n​ ​t​h​e​ ​s​c​o​p​e​ ​a​n​d​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​o​f​ ​t​h​e​ ​p​r​o​j​e​c​t​.​ ​F​o​r​ ​r​e​f​e​r​e​n​c​e​,​ ​p​a​s​t​ ​p​r​o​j​e​c​t​s​ ​h​a​v​e​ ​r​a​n​g​e​d​ ​b​e​t​w​e​e​n​ ​$​3​0​ ​-​ ​$​4​0​ ​(​h​o​u​r​l​y​,​ ​4​0​+​ ​p​e​r​ ​w​e​e​k​)​.​ ​<​b​r​>​<​b​r​>​ ​O​n​ ​t​h​e​ ​c​a​l​l​,​ ​w​e​ ​w​i​l​l​ ​s​e​e​k​ ​t​o​ ​i​d​e​n​t​i​f​y​ ​s​p​e​c​i​f​i​c​s​ ​a​n​d​ ​o​b​j​e​c​t​i​v​e​s​ ​t​h​a​t​ ​c​a​n​ ​a​f​f​e​c​t​ ​t​h​e​ ​c​o​s​t​.​ ​T​h​e​s​e​ ​a​r​e​ ​t​h​i​n​g​s​ ​l​i​k​e​ ​w​h​a​t​ ​t​y​p​e​ ​o​f​ ​p​r​o​j​e​c​t​,​ ​w​h​i​c​h​ ​t​e​c​h​ ​s​t​a​c​k​ ​t​o​ ​c​h​o​o​s​e​,​ ​t​i​m​e​l​i​n​e​,​ ​c​o​m​p​l​e​x​i​t​y​,​ ​f​r​o​n​t​e​n​d​/​b​a​c​k​e​n​d​/​f​u​l​l​s​t​a​c​k​,​ ​e​t​c​.​ ​A​l​l​ ​t​h​e​s​e​ ​w​i​l​l​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​t​h​e​ ​c​o​s​t​ ​a​n​d​ ​w​i​l​l​ ​v​a​r​y​ ​f​r​o​m​ ​p​r​o​j​e​c​t​ ​t​o​ ​p​r​o​j​e​c​t​.
				 */
				answer: string
			}
			'2': {
				/**
				 * H​o​w​ ​l​o​n​g​ ​w​i​l​l​ ​t​h​e​ ​w​o​r​k​ ​t​a​k​e​ ​f​r​o​m​ ​s​t​a​r​t​ ​t​o​ ​f​i​n​i​s​h​?
				 */
				question: string
				/**
				 * I​t​ ​w​i​l​l​ ​d​e​p​e​n​d​ ​o​n​ ​t​h​e​ ​s​c​o​p​e​ ​o​f​ ​t​h​e​ ​p​r​o​j​e​c​t​.​ ​<​b​r​>​<​b​r​>​ ​<​u​l​ ​c​l​a​s​s​=​"​l​i​s​t​-​d​i​s​c​ ​m​l​-​5​"​>​<​l​i​>​I​f​ ​i​t​ ​i​s​ ​a​ ​f​r​o​n​t​e​n​d​ ​a​p​p​l​i​c​a​t​i​o​n​,​ ​i​t​ ​w​i​l​l​ ​t​a​k​e​ ​l​e​s​s​ ​t​i​m​e​.​<​/​l​i​>​<​l​i​>​I​f​ ​i​t​ ​i​n​v​o​l​v​e​s​ ​c​o​m​p​l​e​x​i​t​y​ ​w​i​t​h​ ​b​a​c​k​e​n​d​ ​s​t​a​c​k​,​ ​i​t​ ​w​i​l​l​ ​t​a​k​e​ ​s​l​i​g​h​t​l​y​ ​l​o​n​g​e​r​ ​t​h​a​n​ ​b​e​f​o​r​e​.​<​/​l​i​>​<​l​i​>​F​o​r​ ​f​u​l​l​s​t​a​c​k​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​i​t​h​ ​b​o​t​h​ ​f​r​o​n​t​e​n​d​,​ ​b​a​c​k​e​n​d​,​ ​d​a​t​a​b​a​s​e​,​ ​e​t​c​,​ ​w​i​l​l​ ​t​a​k​e​ ​l​o​n​g​e​r​ ​t​i​m​e​.​ ​A​ ​p​r​e​v​i​o​u​s​ ​p​r​o​j​e​c​t​ ​o​f​ ​m​i​n​e​ ​t​o​o​k​ ​a​l​m​o​s​t​ ​1​2​0​0​+​ ​(​6​+​ ​m​o​n​t​h​s​)​ ​h​o​u​r​s​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​i​n​c​l​u​d​i​n​g​ ​d​e​p​l​o​y​i​n​g​ ​t​o​ ​p​r​o​d​u​c​t​i​o​n​ ​s​e​r​v​e​r​.​<​/​l​i​>​<​l​i​>​F​o​r​ ​m​o​b​i​l​e​ ​a​p​p​l​i​c​a​t​i​o​n​s​,​ ​i​f​ ​i​t​ ​r​e​q​u​i​r​e​s​ ​a​n​ ​A​P​I​ ​t​o​ ​d​e​v​e​l​o​p​,​ ​t​h​e​n​ ​t​h​e​ ​t​i​m​e​ ​w​i​l​l​ ​b​e​ ​a​s​ ​e​q​u​a​l​ ​a​s​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​o​n​e​.​<​/​l​i​>​<​/​u​l​>
				 */
				answer: string
			}
			'3': {
				/**
				 * D​o​ ​y​o​u​ ​o​f​f​e​r​ ​a​n​y​ ​d​e​p​l​o​y​m​e​n​t​ ​s​e​r​v​i​c​e​s​ ​l​i​k​e​ ​D​o​c​k​e​r​,​ ​K​u​b​e​r​n​e​t​e​s​,​ ​A​W​S​/​G​C​P​/​A​z​u​r​e​,​ ​H​e​r​o​k​u​,​ ​V​P​S​,​ ​S​t​a​t​i​c​/​S​h​a​r​e​d​ ​H​o​s​t​i​n​g​,​ ​e​t​c​?
				 */
				question: string
				/**
				 * Y​e​s​,​ ​I​ ​d​o​.​ ​I​f​ ​y​o​u​ ​n​e​e​d​ ​a​n​y​ ​o​f​ ​t​h​e​s​e​ ​s​e​r​v​i​c​e​s​,​ ​I​ ​c​a​n​ ​d​o​ ​t​h​a​t​ ​f​o​r​ ​y​o​u​ ​a​f​t​e​r​ ​f​i​n​i​s​h​i​n​g​ ​t​h​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​n​d​ ​t​e​s​t​i​n​g​ ​p​h​a​s​e​.
				 */
				answer: string
			}
			'4': {
				/**
				 * D​o​ ​y​o​u​ ​o​f​f​e​r​ ​a​n​y​ ​m​a​i​n​t​e​n​a​n​c​e​ ​s​e​r​v​i​c​e​s​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e​ ​a​f​t​e​r​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​h​a​s​ ​b​e​e​n​ ​f​i​n​i​s​h​e​d​?
				 */
				question: string
				/**
				 * Y​e​s​,​ ​I​ ​d​o​ ​i​f​ ​i​t​ ​i​s​ ​a​ ​m​a​j​o​r​ ​b​r​e​a​k​d​o​w​n​.​ ​H​o​w​e​v​e​r​,​ ​I​ ​m​a​y​ ​c​h​a​r​g​e​ ​a​d​d​i​t​i​o​n​a​l​ ​f​e​e​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​y​o​u​r​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​a​n​d​ ​m​a​i​n​t​e​n​a​n​c​e​ ​w​o​r​k​l​o​a​d​.
				 */
				answer: string
			}
			'5': {
				/**
				 * C​a​n​ ​y​o​u​ ​h​e​l​p​ ​m​e​ ​t​o​ ​g​r​o​w​ ​m​y​ ​o​w​n​ ​s​t​a​r​t​u​p​?
				 */
				question: string
				/**
				 * Y​e​s​,​ ​o​f​ ​c​o​u​r​s​e​ ​I​ ​c​a​n​.​ ​I​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​w​o​r​k​e​d​ ​w​i​t​h​ ​s​o​m​e​ ​s​t​a​r​t​u​p​s​,​ ​b​u​i​l​d​i​n​g​ ​t​h​e​i​r​ ​i​d​e​a​s​ ​i​n​t​o​ ​r​e​a​l​i​t​y​.​ ​I​ ​a​l​s​o​ ​w​o​r​k​e​d​ ​a​s​ ​a​ ​p​r​o​j​e​c​t​ ​m​a​n​a​g​e​r​ ​i​n​ ​m​y​ ​p​r​e​v​i​o​u​s​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​I​ ​w​o​r​k​e​d​ ​w​i​t​h​.​ ​F​r​o​m​ ​b​u​i​l​d​i​n​g​ ​a​ ​M​i​n​i​m​u​m​ ​V​i​a​b​l​e​ ​P​r​o​d​u​c​t​ ​(​M​V​P​)​ ​t​o​ ​l​a​u​n​c​h​ ​a​n​d​ ​g​r​o​w​t​h​,​ ​I​ ​c​a​n​ ​h​e​l​p​ ​y​o​u​ ​i​n​ ​e​a​c​h​ ​s​t​e​p​.
				 */
				answer: string
			}
			'6': {
				/**
				 * D​o​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​a​g​e​n​c​y​ ​o​r​ ​t​e​a​m​ ​t​o​ ​w​o​r​k​ ​w​i​t​h​ ​y​o​u​?
				 */
				question: string
				/**
				 * Y​e​s​,​ ​I​ ​h​a​v​e​ ​a​ ​t​e​a​m​ ​o​f​ ​5​ ​m​e​m​b​e​r​s​ ​w​h​o​ ​a​r​e​ ​e​x​p​e​r​t​s​ ​i​n​ ​t​h​e​i​r​ ​o​w​n​ ​f​i​e​l​d​.​ ​W​e​'​r​e​ ​w​o​r​k​i​n​g​ ​t​o​g​e​t​h​e​r​ ​f​o​r​ ​t​h​e​ ​l​a​s​t​ ​3​ ​y​e​a​r​s​.​ ​M​o​r​e​o​v​e​r​,​ ​w​e​ ​a​r​e​ ​p​l​a​n​n​i​n​g​ ​t​o​ ​e​x​p​a​n​d​ ​o​u​r​ ​t​e​a​m​ ​w​i​t​h​ ​a​n​ ​a​g​e​n​c​y​ ​i​n​ ​t​h​e​ ​n​e​a​r​ ​f​u​t​u​r​e​.
				 */
				answer: string
			}
		}
	}
	projectShowcase: {
		/**
		 * P​r​o​j​e​c​t​s​ ​t​h​a​t​ ​I​ ​w​o​r​k​e​d​ ​o​n​ ​o​r​ ​w​o​r​k​i​n​g
		 */
		title: string
		/**
		 * I​ ​h​a​v​e​ ​d​e​s​i​g​n​e​d​,​ ​d​e​v​e​l​o​p​e​d​,​ ​a​n​d​ ​d​e​l​i​v​e​r​e​d​ ​p​r​o​j​e​c​t​s​ ​f​o​r​ ​m​a​n​y​ ​c​l​i​e​n​t​s​,​ ​b​o​t​h​ ​l​a​r​g​e​ ​a​n​d​ ​s​m​a​l​l​.​ ​H​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​w​o​r​t​h​ ​t​o​ ​m​e​n​t​i​o​n​.
		 */
		description: string
		projects: {
			'0': {
				/**
				 * S​p​l​a​s​h​r​ ​C​l​i​e​n​t​ ​S​a​a​S
				 */
				title: string
				/**
				 * C​l​i​e​n​t​ ​J​o​b
				 */
				type: string
				/**
				 * S​p​l​a​s​h​r
				 */
				company: string
				/**
				 * J​u​n​e​ ​2​0​2​1
				 */
				completed: string
				/**
				 * <​p​>​S​p​l​a​s​h​r​ ​i​s​ ​a​n​ ​a​d​v​e​r​t​i​s​i​n​g​ ​c​o​m​p​a​n​y​ ​f​r​o​m​ ​F​r​a​n​c​h​.​ ​I​ ​c​r​e​a​t​e​d​ ​t​h​e​i​r​ ​S​a​a​S​ ​a​p​p​l​i​c​a​t​i​o​n​ ​w​h​e​r​e​ ​t​h​e​y​ ​c​a​n​ ​m​a​n​a​g​e​ ​t​h​e​i​r​ ​a​s​s​e​t​s​ ​w​i​t​h​ ​t​h​e​i​r​ ​c​l​i​e​n​t​s​,​ ​m​o​r​e​ ​l​i​k​e​ ​a​ ​c​u​s​t​o​m​e​r​-​m​a​n​a​g​e​r​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​.​<​/​p​>​<​p​>​T​h​e​y​ ​m​a​k​e​ ​s​h​o​r​t​ ​a​d​s​ ​f​o​r​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​p​l​a​t​f​o​r​m​s​ ​l​i​k​e​ ​T​i​k​t​o​k​,​ ​I​n​s​t​a​g​r​a​m​,​ ​F​a​c​e​b​o​o​k​,​ ​Y​o​u​t​u​b​e​,​ ​e​t​c​.​ ​I​ ​h​a​d​ ​a​ ​g​r​e​a​t​ ​t​i​m​e​ ​w​o​r​k​i​n​g​ ​w​i​t​h​ ​t​h​e​i​r​ ​d​o​m​a​i​n​ ​e​x​p​e​r​t​s​ ​t​o​ ​t​a​c​k​l​e​ ​v​a​r​i​o​u​s​ ​p​r​o​b​l​e​m​s​ ​i​n​c​l​u​d​i​n​g​ ​v​i​d​e​o​ ​d​a​t​a​ ​s​t​r​e​a​m​ ​&​ ​m​a​n​a​g​e​m​e​n​t​.​ ​A​l​s​o​,​ ​w​o​r​k​e​d​ ​w​i​t​h​ ​d​i​f​f​e​r​e​n​t​ ​A​P​I​s​ ​l​i​k​e​ ​F​r​a​m​e​.​i​o​,​ ​G​o​o​g​l​e​ ​S​h​e​e​t​,​ ​d​o​c​s​,​ ​s​l​i​d​e​s​,​ ​e​t​c​.​<​/​p​>​<​p​>​T​h​i​s​ ​w​a​s​ ​o​n​e​ ​o​f​ ​a​ ​k​i​n​d​ ​p​r​o​j​e​c​t​ ​w​h​e​r​e​ ​I​ ​g​e​t​ ​a​ ​v​a​s​t​ ​k​n​o​w​l​e​d​g​e​ ​a​b​o​u​t​ ​c​o​m​p​l​e​x​ ​s​o​f​t​w​a​r​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​&​ ​a​r​c​h​i​t​e​c​t​u​r​e​.​ ​I​t​ ​w​a​s​ ​a​ ​h​u​g​e​ ​b​o​o​s​t​ ​o​n​ ​m​y​ ​c​a​r​e​e​r​ ​a​t​ ​t​h​a​t​ ​t​i​m​e​.​<​/​p​>
				 */
				description: string
				banners: {
					'0': {
						/**
						 * S​p​l​a​s​h​r​M​a​i​n
						 */
						banner: string
						'class': string
					}
					'1': {
						/**
						 * S​p​l​a​s​h​r​1
						 */
						banner: string
						/**
						 * -​t​o​p​-​1​0​ ​l​e​f​t​-​0​ ​-​r​o​t​a​t​e​-​1​2
						 */
						'class': string
					}
					'2': {
						/**
						 * S​p​l​a​s​h​r​2
						 */
						banner: string
						/**
						 * t​o​p​-​1​0​ ​l​e​f​t​-​4​0​ ​-​r​o​t​a​t​e​-​1​2
						 */
						'class': string
					}
					'3': {
						/**
						 * S​p​l​a​s​h​r​3
						 */
						banner: string
						/**
						 * t​o​p​-​4​0​ ​l​e​f​t​-​4​0​ ​r​o​t​a​t​e​-​3
						 */
						'class': string
					}
					'4': {
						/**
						 * S​p​l​a​s​h​r​4
						 */
						banner: string
						/**
						 * -​b​o​t​t​o​m​-​2​0​ ​l​e​f​t​-​2​8​ ​r​o​t​a​t​e​-​6
						 */
						'class': string
					}
					'5': {
						/**
						 * S​p​l​a​s​h​r​5
						 */
						banner: string
						/**
						 * -​b​o​t​t​o​m​-​2​8​ ​-​l​e​f​t​-​5​ ​r​o​t​a​t​e​-​1​2
						 */
						'class': string
					}
				}
			}
			'1': {
				/**
				 * S​a​l​e​s​ ​R​e​p​o​r​t​ ​B​u​i​l​d​e​r
				 */
				title: string
				/**
				 * R​e​m​o​t​e​ ​J​o​b
				 */
				type: string
				/**
				 * P​a​t​t​e​r​n​.​I​n​c
				 */
				company: string
				/**
				 * D​e​c​e​m​b​e​r​ ​2​0​1​9
				 */
				completed: string
				/**
				 * <​p​>​T​h​i​s​ ​i​s​ ​a​ ​r​e​p​o​r​t​ ​b​u​i​l​d​e​r​ ​p​r​o​j​e​c​t​ ​f​o​r​ ​A​m​a​z​o​n​,​ ​W​a​l​m​a​r​t​,​ ​S​h​o​p​i​f​y​,​ ​T​a​r​g​e​t​.​c​o​m​,​ ​e​t​c​.​ ​W​e​ ​d​e​v​e​l​o​p​e​d​ ​s​o​m​e​ ​s​c​r​a​p​p​e​r​s​ ​f​o​r​ ​t​h​e​s​e​ ​s​i​t​e​s​ ​a​n​d​ ​c​o​l​l​e​c​t​e​d​ ​a​ ​l​a​r​g​e​ ​n​u​m​b​e​r​ ​o​f​ ​d​a​t​a​.​ ​T​h​e​n​ ​w​e​ ​u​s​e​ ​t​h​o​s​e​ ​d​a​t​a​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​m​o​r​e​ ​t​h​a​n​ ​1​0​0​ ​t​y​p​e​s​ ​o​f​ ​r​e​p​o​r​t​s​ ​b​o​t​h​ ​i​n​ ​G​o​o​g​l​e​ ​S​l​i​d​e​ ​a​n​d​ ​P​D​F​ ​f​o​r​m​a​t​.​ ​I​n​ ​t​h​e​ ​r​e​p​o​r​t​ ​b​u​i​l​d​e​r​,​ ​t​h​e​r​e​ ​a​r​e​ ​m​a​n​y​ ​t​o​o​l​s​ ​t​h​a​t​ ​u​s​e​r​s​ ​c​a​n​ ​u​s​e​ ​t​o​ ​c​r​e​a​t​e​ ​t​h​e​i​r​ ​r​e​p​o​r​t​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​i​r​ ​p​r​e​f​e​r​e​n​c​e​s​.​ ​T​h​e​y​ ​c​a​n​ ​s​h​a​r​e​ ​t​h​o​s​e​ ​r​e​p​o​r​t​s​ ​w​i​t​h​ ​t​h​e​ ​s​a​l​e​s​ ​t​e​a​m​ ​o​r​ ​a​n​y​ ​b​u​s​i​n​e​s​s​ ​p​e​r​s​o​n​n​e​l​ ​t​h​r​o​u​g​h​ ​E​m​a​i​l​s​ ​s​i​n​c​e​ ​a​l​l​ ​t​h​e​ ​r​e​p​o​r​t​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​i​n​ ​t​h​e​ ​A​m​a​z​o​n​ ​S​3​ ​b​u​c​k​e​t​<​/​p​>​<​p​>​T​h​e​r​e​ ​a​r​e​ ​a​ ​l​o​t​ ​o​f​ ​f​e​a​t​u​r​e​s​ ​t​h​a​t​ ​I​ ​c​a​n​'​t​ ​e​x​p​l​a​i​n​ ​b​e​c​a​u​s​e​ ​o​f​ ​s​o​m​e​ ​p​e​r​m​i​s​s​i​o​n​ ​i​s​s​u​e​ ​b​u​t​ ​I​ ​h​o​p​e​ ​y​o​u​ ​g​e​t​ ​t​h​e​ ​b​a​s​i​c​ ​o​v​e​r​v​i​e​w​ ​f​r​o​m​ ​h​e​r​e​.​<​/​p​>​<​a​ ​h​r​e​f​=​'​h​t​t​p​s​:​/​/​y​o​u​t​u​.​b​e​/​k​w​A​n​O​K​U​5​v​y​g​'​ ​t​a​r​g​e​t​=​'​_​b​l​a​n​k​'​ ​r​e​l​=​'​n​o​o​p​e​n​e​r​'​ ​c​l​a​s​s​=​'​u​n​d​e​r​l​i​n​e​'​>​V​i​d​e​o​ ​D​e​m​o​<​/​a​>
				 */
				description: string
				banners: {
					'0': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​M​a​i​n
						 */
						banner: string
						'class': string
					}
					'1': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​1
						 */
						banner: string
						/**
						 * -​t​o​p​-​2​0​ ​r​i​g​h​t​-​1​6​ ​r​o​t​a​t​e​-​1​2
						 */
						'class': string
					}
					'2': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​2
						 */
						banner: string
						/**
						 * t​o​p​-​0​ ​r​i​g​h​t​-​4​0​ ​r​o​t​a​t​e​-​6
						 */
						'class': string
					}
					'3': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​3
						 */
						banner: string
						/**
						 * t​o​p​-​2​0​ ​r​i​g​h​t​-​5​6​ ​-​r​o​t​a​t​e​-​3
						 */
						'class': string
					}
					'4': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​4
						 */
						banner: string
						/**
						 * t​o​p​-​4​8​ ​r​i​g​h​t​-​4​0​ ​-​r​o​t​a​t​e​-​6
						 */
						'class': string
					}
					'5': {
						/**
						 * R​e​p​o​r​t​B​u​i​l​d​e​r​5
						 */
						banner: string
						/**
						 * -​b​o​t​t​o​m​-​2​8​ ​r​i​g​h​t​-​2​0​ ​-​r​o​t​a​t​e​-​6
						 */
						'class': string
					}
				}
			}
		}
	}
	feedbackPage: {
		/**
		 * W​h​a​t​ ​p​e​o​p​l​e​ ​a​r​e​ ​s​a​y​i​n​g​ ​a​b​o​u​t​ ​m​e​?
		 */
		title: string
		/**
		 * I​ ​a​m​ ​a​n​ ​e​x​p​e​r​i​e​n​c​e​d​ ​a​n​d​ ​e​x​p​e​r​t​ ​d​e​v​e​l​o​p​e​r​ ​w​h​o​ ​y​o​u​ ​w​i​l​l​ ​l​o​v​e​ ​w​o​r​k​i​n​g​ ​w​i​t​h​.​ ​B​u​t​ ​d​o​n​'​t​ ​j​u​s​t​ ​t​a​k​e​ ​m​y​ ​w​o​r​d​ ​f​o​r​ ​i​t​.​ ​S​e​e​ ​w​h​a​t​ ​s​o​m​e​ ​o​f​ ​m​y​ ​c​l​i​e​n​t​s​ ​h​a​v​e​ ​t​o​ ​s​a​y​.
		 */
		description: string
		keywords: string
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
	}
}

export type TranslationFunctions = {
	/**
	 * Irfanul Islam
	 */
	appName: () => LocalizedString
	/**
	 * Build your dream product faster with industry-standard tools and best practices | Irfanul Islam
	 */
	title: () => LocalizedString
	/**
	 * Irfanul Islam  is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. He is also a big fan of open-source and loves to contribute to open-source projects. So if you want to build your dream product faster with industry-standard tools and best practices then you are in the right place.
	 */
	description: () => LocalizedString
	/**
	 * Full-stack developer, Web development, Frontend development, Backend development, JavaScript, HTML, CSS, Responsive design, User interface (UI), User experience (UX), Database design, Server-side scripting, API integration, Software architecture, Code optimization, Version control (e.g., Git), Agile development, Problem-solving, Project management, Client collaboration, Irfanul Islam
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	common: {
		/**
		 * etc
		 */
		etc: () => LocalizedString
		/**
		 * and many more...
		 */
		andManyMore: () => LocalizedString
		/**
		 * Build your dream product faster with industry-standard tools and best practices
		 */
		slogan: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
		/**
		 * Toggle navigation menu
		 */
		toggleNavigationMenu: () => LocalizedString
	}
	profile: {
		/**
		 * Irfanul Islam
		 */
		fullName: () => LocalizedString
		/**
		 * irfanulislamdu@gmail.com
		 */
		email: () => LocalizedString
		/**
		 * Full-stack developer @shamscorner
		 */
		designation: () => LocalizedString
		/**
		 * https://www.upwork.com/freelancers/~017677c090f8fd7a34
		 */
		upworkLink: () => LocalizedString
		/**
		 * https://www.facebook.com/Mdshohaan
		 */
		facebookLink: () => LocalizedString
		/**
		 * https://x.com/IslamIrfan20544
		 */
		xLink: () => LocalizedString
		/**
		 * https://www.linkedin.com/in/mohammadirfanulislam/
		 */
		linkedinLink: () => LocalizedString
		/**
		 * https://github.com/mdshohaan
		 */
		githubLink: () => LocalizedString
	}
	appLogo: {
		/**
		 * Irfanul Islam  is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. He is also a big fan of open-source and loves to contribute to open-source projects. So if you want to build your dream product faster with industry-standard tools and best practices then you are in the right place.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * Irfanul Islam Logo
		 */
		alt: () => LocalizedString
	}
	schemaMarkup: {
		/**
		 * Corporation
		 */
		type: () => LocalizedString
		/**
		 * Irfanul Islam
		 */
		name: () => LocalizedString
		/**
		 * Irfanul Islam  is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. He is also a big fan of open-source and loves to contribute to open-source projects. So if you want to build your dream product faster with industry-standard tools and best practices then you are in the right place.
		 */
		markupDescription: () => LocalizedString
		founder: {
			'0': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Irfanul Islam
				 */
				name: () => LocalizedString
			}
		}
		/**
		 * 2025-07-04
		 */
		foundingDate: () => LocalizedString
		contactPoint: {
			'0': {
				/**
				 * ContactPoint
				 */
				type: () => LocalizedString
				/**
				 * irfanulislamdu@gmail.com
				 */
				email: () => LocalizedString
				telephone: () => LocalizedString
				/**
				 * customer service
				 */
				contactType: () => LocalizedString
			}
		}
	}
	errorPage: {
		/**
		 * 404
		 */
		title: () => LocalizedString
		/**
		 * Not found
		 */
		subtitle: () => LocalizedString
		/**
		 * 404
		 */
		pageTitle: () => LocalizedString
		/**
		 * Looking for help? Reach out to me at mail@shamscorner.com
		 */
		description: () => LocalizedString
		/**
		 * Support, Contact, Help, 404, Not found
		 */
		keywords: () => LocalizedString
	}
	navbar: {
		items: {
			'0': {
				/**
				 * Experience
				 */
				name: () => LocalizedString
				/**
				 * #section-experience
				 */
				link: () => LocalizedString
			}
			'1': {
				/**
				 * Works I Do
				 */
				name: () => LocalizedString
				/**
				 * #section-works-i-do
				 */
				link: () => LocalizedString
			}
			'2': {
				/**
				 * Projects
				 */
				name: () => LocalizedString
				/**
				 * #section-project-showcase
				 */
				link: () => LocalizedString
			}
			'3': {
				/**
				 * Feedbacks
				 */
				name: () => LocalizedString
				/**
				 * #section-what-others-saying
				 */
				link: () => LocalizedString
			}
			'4': {
				/**
				 * FAQs
				 */
				name: () => LocalizedString
				/**
				 * #section-faqs
				 */
				link: () => LocalizedString
			}
			'5': {
				/**
				 * Let's Talk
				 */
				name: () => LocalizedString
				/**
				 * #section-lets-get-started
				 */
				link: () => LocalizedString
			}
		}
	}
	footer: {
		/**
		 * © All rights reserved 2019
		 */
		copyrights: () => LocalizedString
		/**
		 * Designed and build by myself with <a href="https://nuxtjs.org/" target="_blank" rel="noopener" class="underline">SvelteKit</a> and <a href="https://tailwindcss.com/" target="_blank" rel="noopener" class="underline">Tailwind CSS</a>. Deployed at <a href="https://www.netlify.com/" target="_blank" rel="noopener" class="underline">Vercel</a>
		 */
		remarks: () => LocalizedString
	}
	onboarding: {
		/**
		 * Hi, I'm <span class="font-semibold">Irfanul Islam</span>
		 */
		greeting: () => LocalizedString
		/**
		 * A Passionate Full-stack Web & Mobile Application Developer with Machine Learning Experience
		 */
		title: () => LocalizedString
		/**
		 * Feel free to contact me with any queries you have. We can discuss how we can work together to meet your Business Needs.
		 */
		subtitle: () => LocalizedString
		callToAction: {
			/**
			 * Contact Me
			 */
			contactMe: () => LocalizedString
			/**
			 * Download CV
			 */
			downloadCv: () => LocalizedString
			/**
			 * Download my CV if you prefer to read it later
			 */
			downloadCvTitle: () => LocalizedString
		}
		quickStatistics: {
			stats: {
				'0': {
					/**
					 * Bachelor of Arts (BA)<br> University Of Dhaka<br> 2016 - 2022
					 */
					title: () => LocalizedString
					value: () => LocalizedString
				}
				'1': {
					/**
					 * Job Experience
					 */
					title: () => LocalizedString
					/**
					 * 1 year
					 */
					value: () => LocalizedString
				}
				'2': {
					/**
					 * Total Jobs
					 */
					title: () => LocalizedString
					/**
					 * 1
					 */
					value: () => LocalizedString
				}
				'3': {
					/**
					 * IELTS Score
					 */
					title: () => LocalizedString
					/**
					 * 7.0
					 */
					value: () => LocalizedString
				}
				'4': {
					/**
					 * Helped <span class="text-4xl font-bold mx-1">1</span> startups to reality
					 */
					title: () => LocalizedString
					value: () => LocalizedString
				}
			}
			marketplaces: {
				'0': {
					/**
					 * Check out my Upwork profile
					 */
					title: () => LocalizedString
					/**
					 * https://www.upwork.com/freelancers/~017677c090f8fd7a34
					 */
					link: () => LocalizedString
				}
			}
			socialLinks: {
				'0': {
					/**
					 * My Facebook account
					 */
					title: () => LocalizedString
					/**
					 * facebook
					 */
					icon: () => LocalizedString
					/**
					 * https://www.facebook.com/Mdshohaan
					 */
					link: () => LocalizedString
				}
				'1': {
					/**
					 * My X account
					 */
					title: () => LocalizedString
					/**
					 * x
					 */
					icon: () => LocalizedString
					/**
					 * https://x.com/IslamIrfan20544
					 */
					link: () => LocalizedString
				}
				'2': {
					/**
					 * My Linkedin account
					 */
					title: () => LocalizedString
					/**
					 * linkedin
					 */
					icon: () => LocalizedString
					/**
					 * https://www.linkedin.com/in/mohammadirfanulislam/
					 */
					link: () => LocalizedString
				}
			}
		}
		techStack: {
			/**
			 * My Tech Stack
			 */
			title: () => LocalizedString
			technologies: {
				'0': {
					/**
					 * Frontend
					 */
					title: () => LocalizedString
					items: {
						/**
						 * SvelteKit
						 */
						'0': () => LocalizedString
						/**
						 * ReactJS
						 */
						'1': () => LocalizedString
						/**
						 * NextJS
						 */
						'2': () => LocalizedString
						/**
						 * Astro
						 */
						'3': () => LocalizedString
						/**
						 * TailwindCSS
						 */
						'4': () => LocalizedString
						/**
						 * Vuetify
						 */
						'5': () => LocalizedString
						/**
						 * shadcn-ui
						 */
						'6': () => LocalizedString
						/**
						 * Typescript
						 */
						'7': () => LocalizedString
						/**
						 * Material Design
						 */
						'8': () => LocalizedString
						/**
						 * Vite
						 */
						'9': () => LocalizedString
						/**
						 * DaisyUI
						 */
						'10': () => LocalizedString
						/**
						 * SSR
						 */
						'11': () => LocalizedString
						/**
						 * SSG
						 */
						'12': () => LocalizedString
						/**
						 * SPA
						 */
						'13': () => LocalizedString
						/**
						 * PWA
						 */
						'14': () => LocalizedString
					}
				}
				'1': {
					/**
					 * Backend
					 */
					title: () => LocalizedString
					items: {
						/**
						 * Express
						 */
						'0': () => LocalizedString
						/**
						 * Firebase
						 */
						'1': () => LocalizedString
						/**
						 * Supabase
						 */
						'2': () => LocalizedString
						/**
						 * Convex
						 */
						'3': () => LocalizedString
						/**
						 * PostgreSQL
						 */
						'4': () => LocalizedString
						/**
						 * MongoDB
						 */
						'5': () => LocalizedString
					}
				}
				'2': {
					/**
					 * Others
					 */
					title: () => LocalizedString
					items: {
						/**
						 * Flutter
						 */
						'0': () => LocalizedString
						/**
						 * Python
						 */
						'1': () => LocalizedString
						/**
						 * Scikit Learn
						 */
						'2': () => LocalizedString
						/**
						 * Data mining
						 */
						'3': () => LocalizedString
						/**
						 * Docker
						 */
						'4': () => LocalizedString
						/**
						 * Github Automation
						 */
						'5': () => LocalizedString
						/**
						 * C++
						 */
						'6': () => LocalizedString
					}
				}
			}
			githubProfile: {
				/**
				 * Visit my Github profile
				 */
				title: () => LocalizedString
				/**
				 * https://github.com/mdshohaan
				 */
				link: () => LocalizedString
			}
		}
	}
	areYouInterested: {
		/**
		 * Are you interested?
		 */
		title: () => LocalizedString
		callToAction: {
			/**
			 * Let's Talk
			 */
			letsTalk: () => LocalizedString
		}
	}
	meAtAGlance: {
		/**
		 * -- Me at a glance --
		 */
		title: () => LocalizedString
		profilePicture: {
			/**
			 * Yep! This is me. A raw version of me sitting on a coffee shop. One of my friend took this photo.
			 */
			alt: () => LocalizedString
		}
		infoItems: {
			/**
			 * Tech Enthusiast
			 */
			'0': () => LocalizedString
			/**
			 * I can speak Bengali, Hindi, Urdu,Arabic,English
			 */
			'1': () => LocalizedString
			/**
			 * University Carrom Champion
			 */
			'2': () => LocalizedString
			/**
			 * I like playing Cricket, Football, Badminton, and Table Tennis
			 */
			'3': () => LocalizedString
			/**
			 * I love AI & Data Mining
			 */
			'4': () => LocalizedString
			/**
			 * I am versatile on working schedule
			 */
			'5': () => LocalizedString
			/**
			 * Currently learning advanced Data Structures & Algorithms
			 */
			'6': () => LocalizedString
			/**
			 * 26 years old :)
			 */
			'7': () => LocalizedString
		}
	}
	pastWorkingExperiences: {
		/**
		 * My Past Working Experiences
		 */
		title: () => LocalizedString
		/**
		 * I began freelancing while I was still in university, and I worked on some exciting projects. I will list my main jobs in the order they happened.
		 */
		description: () => LocalizedString
		experiences: {
			'0': {
				/**
				 * 2025
				 */
				year: () => LocalizedString
				/**
				 * shamscorner
				 */
				company: () => LocalizedString
				/**
				 * Full-stack  Developer
				 */
				role: () => LocalizedString
				/**
				 * 01 JANUARY - PRESENT
				 */
				timeline: () => LocalizedString
			}
			'1': {
				/**
				 * 2025
				 */
				year: () => LocalizedString
				/**
				 * Code Alpa
				 */
				company: () => LocalizedString
				/**
				 * Front-end Developer
				 */
				role: () => LocalizedString
				/**
				 * 28 JANUARY - PRESENT
				 */
				timeline: () => LocalizedString
			}
		}
	}
	whatWorkIDo: {
		/**
		 * What kind of works that I do?
		 */
		title: () => LocalizedString
		/**
		 * Here are some services that I usually offer. But feel free to contact with me if you need something else.
		 */
		description: () => LocalizedString
		services: {
			'0': {
				/**
				 * Content Management System (CMS)
				 */
				title: () => LocalizedString
				/**
				 * I offer custom CMS tools making content management easy. With my CMS, you can focus on your core business while I handle the technical side, ensuring your online presence remains engaging.
				 */
				description: () => LocalizedString
				/**
				 * cms
				 */
				image: () => LocalizedString
			}
			'1': {
				/**
				 * Software as a Service (SaaS) Development
				 */
				title: () => LocalizedString
				/**
				 * I offer custom SaaS solutions designed specific to your business. With my SaaS, you can focus on your sales, and delegate the management work to the tools.
				 */
				description: () => LocalizedString
				/**
				 * sass
				 */
				image: () => LocalizedString
			}
			'2': {
				/**
				 * Dashboard or Web Portals Development
				 */
				title: () => LocalizedString
				/**
				 * Let's create a dynamic and informative hub for your business needs. These tools provide live data updates and a user-friendly interface, helping you make informed decisions, predictions, and access crucial information effortlessly.
				 */
				description: () => LocalizedString
				/**
				 * dashboard
				 */
				image: () => LocalizedString
			}
			'3': {
				/**
				 * E-commerce Application Development
				 */
				title: () => LocalizedString
				/**
				 * I provide custom E-commerce solutions tailored to your specific needs. These solutions offer a user-friendly platform for managing your online store, enabling you to concentrate on your business while my tools handle the technical aspects.
				 */
				description: () => LocalizedString
				/**
				 * ecommerce
				 */
				image: () => LocalizedString
			}
			'4': {
				/**
				 * Landing Page Design & Development
				 */
				title: () => LocalizedString
				/**
				 * Let me help you make a strong first impression online with a stunning landing page that captures attention and drive action, making it easy for your audience to engage with your content and offerings.
				 */
				description: () => LocalizedString
				/**
				 * landing
				 */
				image: () => LocalizedString
			}
			'5': {
				/**
				 * Content Sharing Blog Sites Development
				 */
				title: () => LocalizedString
				/**
				 * Let's create an engaging platform for your ideas and stories to shine online. My websites are designed to make it easy for you to publish and share your content with your audience.
				 */
				description: () => LocalizedString
				/**
				 * blog
				 */
				image: () => LocalizedString
			}
			'6': {
				/**
				 * Single Page Application (SPA) Development
				 */
				title: () => LocalizedString
				/**
				 * Let's build a modern, user-friendly application for your specific needs that provide a seamless and responsive user experience. They load quickly and smoothly, delivering a snappy and efficient web interaction. 
				 */
				description: () => LocalizedString
				/**
				 * spa
				 */
				image: () => LocalizedString
			}
			'7': {
				/**
				 * Progressive Web Application (PWA) Development
				 */
				title: () => LocalizedString
				/**
				 * If your business needs a reliable and user-friendly PWA to enhance your online presence. PWAs offer a seamless and engaging user experience across various devices, just like native apps, but they're accessible through web browsers.
				 */
				description: () => LocalizedString
				/**
				 * pwa
				 */
				image: () => LocalizedString
			}
			'8': {
				/**
				 * Scalable & Reliable API Development 
				 */
				title: () => LocalizedString
				/**
				 * I provide scalable and reliable API development, offering both RESTful and GraphQL solutions. Let's build the foundation for seamless data interaction in your systems to support all your customer’s needs.
				 */
				description: () => LocalizedString
				/**
				 * api
				 */
				image: () => LocalizedString
			}
			'9': {
				/**
				 * Social Media Applications Development
				 */
				title: () => LocalizedString
				/**
				 * If you want to create a vibrant and interactive digital space for your brand, I can help building the required infrastructures & platforms to engage with your customers effectively.
				 */
				description: () => LocalizedString
				/**
				 * social
				 */
				image: () => LocalizedString
			}
			'10': {
				/**
				 * Chatbot or Messaging Integrations
				 */
				title: () => LocalizedString
				/**
				 * Let's integrate these tools to streamline and enhance your user engagement. Since AI can automate many solutions, why not incorporate it into your business applications? Let's work together to make that happen.
				 */
				description: () => LocalizedString
				/**
				 * chatbot
				 */
				image: () => LocalizedString
			}
			'11': {
				/**
				 * Mobile Applications Development
				 */
				title: () => LocalizedString
				/**
				 * My expertise lies in creating user-friendly and feature-rich mobile apps that cater to your specific needs. Let's build an app that brings your vision to life and engages your audience on their mobile devices.
				 */
				description: () => LocalizedString
				/**
				 * mobile
				 */
				image: () => LocalizedString
			}
		}
	}
	letsGetStarted: {
		/**
		 * Let's get started
		 */
		title: () => LocalizedString
		/**
		 * Why not start with a simple email first? From there we can decide how we can continue our conversation moving forward.
		 */
		description: () => LocalizedString
		form: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Your e-mail address
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Get Started
			 */
			submit: () => LocalizedString
			/**
			 * Full name
			 */
			fullName: () => LocalizedString
			/**
			 * Message
			 */
			message: () => LocalizedString
			/**
			 * Your message here...
			 */
			messagePlaceholder: () => LocalizedString
			/**
			 * Send
			 */
			send: () => LocalizedString
			/**
			 * Email sent successfully!
			 */
			successMessage: () => LocalizedString
		}
	}
	whatOthersSaying: {
		/**
		 * What people are saying about me?
		 */
		title: () => LocalizedString
		/**
		 * I am an experienced and expert developer who you will love working with. But don't just take my word for it. See what some of my clients have to say.
		 */
		description: () => LocalizedString
		feedbacks: {
			'0': {
				client: {
					/**
					 * Julian Albert
					 */
					fullName: () => LocalizedString
					/**
					 * DPhil Candidate at Oxford Institute
					 */
					position: () => LocalizedString
				}
				/**
				 * Thank you for your support, Shamim! The process was flawless from start to end. He has great communication skills and a thoughtful approach to freelancing. Highly recommended!
				 */
				comment: () => LocalizedString
				/**
				 * md:row-span-4
				 */
				'class': () => LocalizedString
			}
			'1': {
				client: {
					/**
					 * Jack Sharkey
					 */
					fullName: () => LocalizedString
					/**
					 * Upwork client, Frosted IT
					 */
					position: () => LocalizedString
				}
				/**
				 * Shamim did a wonderful job and did it very quickly. He made our website look beautiful and elegant. Would highly recommend.
				 */
				comment: () => LocalizedString
				/**
				 * md:row-start-2 md:col-start-4 md:row-span-4
				 */
				'class': () => LocalizedString
			}
			'2': {
				client: {
					/**
					 * Sean Wright
					 */
					fullName: () => LocalizedString
					/**
					 * Upwork client, Hyped Marketing
					 */
					position: () => LocalizedString
				}
				/**
				 * Shamim is an amazing developer and a real gem. He's talented, smart and has unmatched work ethic. I highly recommend working with him.
				 */
				comment: () => LocalizedString
				/**
				 * md:row-start-5 md:col-start-1 md:row-span-4
				 */
				'class': () => LocalizedString
			}
			'3': {
				client: {
					/**
					 * Landon Cope
					 */
					fullName: () => LocalizedString
					/**
					 * Senior Software developer at Pattern.inc
					 */
					position: () => LocalizedString
				}
				/**
				 * Shamim was great to work with, would recommend for Vue.js and Laravel. Thank you.
				 */
				comment: () => LocalizedString
				/**
				 * md:row-start-4 md:col-start-2 md:row-span-4
				 */
				'class': () => LocalizedString
			}
			'4': {
				client: {
					/**
					 * Jack Sharkey
					 */
					fullName: () => LocalizedString
					/**
					 * Upwork client, Frosted IT
					 */
					position: () => LocalizedString
				}
				/**
				 * Shamim is a beast! Highly recommend.
				 */
				comment: () => LocalizedString
				/**
				 * md:row-start-5 md:col-start-3 md:row-span-4
				 */
				'class': () => LocalizedString
			}
			'5': {
				client: {
					/**
					 * Brandon Barclay
					 */
					fullName: () => LocalizedString
					/**
					 * Upwork client, Pattern.inc
					 */
					position: () => LocalizedString
				}
				/**
				 * Putting on a different contract. Great developer.
				 */
				comment: () => LocalizedString
				/**
				 * md:row-start-6 md:col-start-4 md:row-span-4
				 */
				'class': () => LocalizedString
			}
		}
		/**
		 * Check out more if you want
		 */
		seeMore: () => LocalizedString
	}
	thingsIWantToLearn: {
		/**
		 * Things I want to learn
		 */
		title: () => LocalizedString
		/**
		 * I have been fortunate enough to learn many things throughout my career, but I still have a long way to go. This is a list of some of the technologies that I would love to learn.
		 */
		description: () => LocalizedString
		technologies: {
			'0': {
				/**
				 * ML5
				 */
				name: () => LocalizedString
				/**
				 * false
				 */
				done: () => LocalizedString
			}
			'1': {
				/**
				 * ThreeJS
				 */
				name: () => LocalizedString
				/**
				 * false
				 */
				done: () => LocalizedString
			}
			'2': {
				/**
				 * Tensorflow.js
				 */
				name: () => LocalizedString
				/**
				 * false
				 */
				done: () => LocalizedString
			}
			'3': {
				/**
				 * Drizzle ORM
				 */
				name: () => LocalizedString
				/**
				 * false
				 */
				done: () => LocalizedString
			}
			'4': {
				/**
				 * Miko ORM
				 */
				name: () => LocalizedString
				/**
				 * false
				 */
				done: () => LocalizedString
			}
			'5': {
				/**
				 * Automation
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'6': {
				/**
				 * Web Scrapping
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'7': {
				/**
				 * Algorithms
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'8': {
				/**
				 * Data Structures
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'9': {
				/**
				 * SvelteKit
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'10': {
				/**
				 * Vue
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'11': {
				/**
				 * Nuxt
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'12': {
				/**
				 * Astro
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'13': {
				/**
				 * React
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'14': {
				/**
				 * NextJS
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'15': {
				/**
				 * TailwindCSS
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'16': {
				/**
				 * Vuetify
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'17': {
				/**
				 * Shadcn UI
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'18': {
				/**
				 * Typescript
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'19': {
				/**
				 * Material Design
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'20': {
				/**
				 * Vite
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'21': {
				/**
				 * Websocket
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'22': {
				/**
				 * SSR
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'23': {
				/**
				 * SSG
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'24': {
				/**
				 * SPA
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'25': {
				/**
				 * PWA
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'26': {
				/**
				 * NestJS
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'27': {
				/**
				 * Express
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'28': {
				/**
				 * Fastify
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'29': {
				/**
				 * Firebase
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'30': {
				/**
				 * Supabase
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'31': {
				/**
				 * Appwrite
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'32': {
				/**
				 * DGraph
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'33': {
				/**
				 * Prisma
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'34': {
				/**
				 * Graphbase
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'35': {
				/**
				 * GraphQL
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'36': {
				/**
				 * MySQL
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'37': {
				/**
				 * SQLite
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'38': {
				/**
				 * PostgreSQL
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'39': {
				/**
				 * MongoDB
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'40': {
				/**
				 * Redis
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'41': {
				/**
				 * TypeORM
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'42': {
				/**
				 * Microservices
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'43': {
				/**
				 * MonoRepo
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'44': {
				/**
				 * TurboRepo
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'45': {
				/**
				 * Electron
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'46': {
				/**
				 * Flutter
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'47': {
				/**
				 * Python
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'48': {
				/**
				 * Scikit Learn
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'49': {
				/**
				 * Data mining
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'50': {
				/**
				 * Machine learning
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'51': {
				/**
				 * Docker
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'52': {
				/**
				 * AWS
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'53': {
				/**
				 * Azure
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'54': {
				/**
				 * GCP
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'55': {
				/**
				 * CI/CD
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'56': {
				/**
				 * Kubernetes
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'57': {
				/**
				 * Java
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'58': {
				/**
				 * Dart
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'59': {
				/**
				 * PHP
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'60': {
				/**
				 * C
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
			'61': {
				/**
				 * C++
				 */
				name: () => LocalizedString
				/**
				 * true
				 */
				done: () => LocalizedString
			}
		}
	}
	faqs: {
		/**
		 * Frequently Asked Questions
		 */
		title: () => LocalizedString
		/**
		 * Here are some frequently asked questions. If you have any other questions, feel free to contact me.
		 */
		description: () => LocalizedString
		questions: {
			'0': {
				/**
				 * Where can I see your professional work?
				 */
				question: () => LocalizedString
				/**
				 * Thank you for asking! For full transparency, I am unable to show my best work publicly because they are locked behind non-disclosure agreements. If you contact me however, I will be able to share them with you in private during the call. <br><br> If that is not enough for you, I am happy to report that this entire website that you are in, is designed, crafted and fully built by me using Nuxt and Tailwind CSS (JamStack Hosted), and thus can be considered as part of my professional work. I hope that it is satisfactory to your liking 😊
				 */
				answer: () => LocalizedString
			}
			'1': {
				/**
				 * How much does it cost to get started?
				 */
				question: () => LocalizedString
				/**
				 * It will depend upon the scope and requirements of the project. For reference, past projects have ranged between $30 - $40 (hourly, 40+ per week). <br><br> On the call, we will seek to identify specifics and objectives that can affect the cost. These are things like what type of project, which tech stack to choose, timeline, complexity, frontend/backend/fullstack, etc. All these will contribute to the cost and will vary from project to project.
				 */
				answer: () => LocalizedString
			}
			'2': {
				/**
				 * How long will the work take from start to finish?
				 */
				question: () => LocalizedString
				/**
				 * It will depend on the scope of the project. <br><br> <ul class="list-disc ml-5"><li>If it is a frontend application, it will take less time.</li><li>If it involves complexity with backend stack, it will take slightly longer than before.</li><li>For fullstack applications with both frontend, backend, database, etc, will take longer time. A previous project of mine took almost 1200+ (6+ months) hours to complete including deploying to production server.</li><li>For mobile applications, if it requires an API to develop, then the time will be as equal as the previous one.</li></ul>
				 */
				answer: () => LocalizedString
			}
			'3': {
				/**
				 * Do you offer any deployment services like Docker, Kubernetes, AWS/GCP/Azure, Heroku, VPS, Static/Shared Hosting, etc?
				 */
				question: () => LocalizedString
				/**
				 * Yes, I do. If you need any of these services, I can do that for you after finishing the development and testing phase.
				 */
				answer: () => LocalizedString
			}
			'4': {
				/**
				 * Do you offer any maintenance services in the future after the project has been finished?
				 */
				question: () => LocalizedString
				/**
				 * Yes, I do if it is a major breakdown. However, I may charge additional fees according to your requirements and maintenance workload.
				 */
				answer: () => LocalizedString
			}
			'5': {
				/**
				 * Can you help me to grow my own startup?
				 */
				question: () => LocalizedString
				/**
				 * Yes, of course I can. I have already worked with some startups, building their ideas into reality. I also worked as a project manager in my previous company that I worked with. From building a Minimum Viable Product (MVP) to launch and growth, I can help you in each step.
				 */
				answer: () => LocalizedString
			}
			'6': {
				/**
				 * Do you have any agency or team to work with you?
				 */
				question: () => LocalizedString
				/**
				 * Yes, I have a team of 5 members who are experts in their own field. We're working together for the last 3 years. Moreover, we are planning to expand our team with an agency in the near future.
				 */
				answer: () => LocalizedString
			}
		}
	}
	projectShowcase: {
		/**
		 * Projects that I worked on or working
		 */
		title: () => LocalizedString
		/**
		 * I have designed, developed, and delivered projects for many clients, both large and small. Here are some worth to mention.
		 */
		description: () => LocalizedString
		projects: {
			'0': {
				/**
				 * Splashr Client SaaS
				 */
				title: () => LocalizedString
				/**
				 * Client Job
				 */
				type: () => LocalizedString
				/**
				 * Splashr
				 */
				company: () => LocalizedString
				/**
				 * June 2021
				 */
				completed: () => LocalizedString
				/**
				 * <p>Splashr is an advertising company from Franch. I created their SaaS application where they can manage their assets with their clients, more like a customer-manager web application.</p><p>They make short ads for social media platforms like Tiktok, Instagram, Facebook, Youtube, etc. I had a great time working with their domain experts to tackle various problems including video data stream & management. Also, worked with different APIs like Frame.io, Google Sheet, docs, slides, etc.</p><p>This was one of a kind project where I get a vast knowledge about complex software development & architecture. It was a huge boost on my career at that time.</p>
				 */
				description: () => LocalizedString
				banners: {
					'0': {
						/**
						 * SplashrMain
						 */
						banner: () => LocalizedString
						'class': () => LocalizedString
					}
					'1': {
						/**
						 * Splashr1
						 */
						banner: () => LocalizedString
						/**
						 * -top-10 left-0 -rotate-12
						 */
						'class': () => LocalizedString
					}
					'2': {
						/**
						 * Splashr2
						 */
						banner: () => LocalizedString
						/**
						 * top-10 left-40 -rotate-12
						 */
						'class': () => LocalizedString
					}
					'3': {
						/**
						 * Splashr3
						 */
						banner: () => LocalizedString
						/**
						 * top-40 left-40 rotate-3
						 */
						'class': () => LocalizedString
					}
					'4': {
						/**
						 * Splashr4
						 */
						banner: () => LocalizedString
						/**
						 * -bottom-20 left-28 rotate-6
						 */
						'class': () => LocalizedString
					}
					'5': {
						/**
						 * Splashr5
						 */
						banner: () => LocalizedString
						/**
						 * -bottom-28 -left-5 rotate-12
						 */
						'class': () => LocalizedString
					}
				}
			}
			'1': {
				/**
				 * Sales Report Builder
				 */
				title: () => LocalizedString
				/**
				 * Remote Job
				 */
				type: () => LocalizedString
				/**
				 * Pattern.Inc
				 */
				company: () => LocalizedString
				/**
				 * December 2019
				 */
				completed: () => LocalizedString
				/**
				 * <p>This is a report builder project for Amazon, Walmart, Shopify, Target.com, etc. We developed some scrappers for these sites and collected a large number of data. Then we use those data to generate more than 100 types of reports both in Google Slide and PDF format. In the report builder, there are many tools that users can use to create their reports according to their preferences. They can share those reports with the sales team or any business personnel through Emails since all the reports are stored in the Amazon S3 bucket</p><p>There are a lot of features that I can't explain because of some permission issue but I hope you get the basic overview from here.</p><a href='https://youtu.be/kwAnOKU5vyg' target='_blank' rel='noopener' class='underline'>Video Demo</a>
				 */
				description: () => LocalizedString
				banners: {
					'0': {
						/**
						 * ReportBuilderMain
						 */
						banner: () => LocalizedString
						'class': () => LocalizedString
					}
					'1': {
						/**
						 * ReportBuilder1
						 */
						banner: () => LocalizedString
						/**
						 * -top-20 right-16 rotate-12
						 */
						'class': () => LocalizedString
					}
					'2': {
						/**
						 * ReportBuilder2
						 */
						banner: () => LocalizedString
						/**
						 * top-0 right-40 rotate-6
						 */
						'class': () => LocalizedString
					}
					'3': {
						/**
						 * ReportBuilder3
						 */
						banner: () => LocalizedString
						/**
						 * top-20 right-56 -rotate-3
						 */
						'class': () => LocalizedString
					}
					'4': {
						/**
						 * ReportBuilder4
						 */
						banner: () => LocalizedString
						/**
						 * top-48 right-40 -rotate-6
						 */
						'class': () => LocalizedString
					}
					'5': {
						/**
						 * ReportBuilder5
						 */
						banner: () => LocalizedString
						/**
						 * -bottom-28 right-20 -rotate-6
						 */
						'class': () => LocalizedString
					}
				}
			}
		}
	}
	feedbackPage: {
		/**
		 * What people are saying about me?
		 */
		title: () => LocalizedString
		/**
		 * I am an experienced and expert developer who you will love working with. But don't just take my word for it. See what some of my clients have to say.
		 */
		description: () => LocalizedString
		keywords: () => LocalizedString
	}
	errors: {
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
	}
}

export type Formatters = {}
